-- ammo.lua
return {
		["BP_Ammo_12G_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_12G.Default__BP_Ammo_12G_C",
		},
		["BP_Ammo_357_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_357.Default__BP_Ammo_357_C",
		},
		["BP_Ammo_38Special_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_38Special.Default__BP_Ammo_38Special_C",
		},
		["BP_Ammo_45ACP_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_45ACP.Default__BP_Ammo_45ACP_C",
		},
		["BP_Ammo_50MG_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_50MG.Default__BP_Ammo_50MG_C",
		},
		["BP_Ammo_556_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_556.Default__BP_Ammo_556_C",
		},
		["BP_Ammo_57_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_57.Default__BP_Ammo_57_C",
		},
		["BP_Ammo_762_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_762.Default__BP_Ammo_762_C",
		},
		["BP_Ammo_9mm_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_9mm.Default__BP_Ammo_9mm_C",
		},
		["BP_Ammo_AT4_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_AT4.Default__BP_Ammo_AT4_C",
		},
		["BP_Ammo_Flare_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_Flare.Default__BP_Ammo_Flare_C",
		},
		["BP_Ammo_LaserGun_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_LaserGun.Default__BP_Ammo_LaserGun_C",
		},
		["BP_Ammo_Taser_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Ammo_Taser.Default__BP_Ammo_Taser_C",
		},
		["BP_Magazine_AK_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_AK.Default__BP_Magazine_AK_C",
		},
		["BP_Magazine_Bolt1911_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_Bolt1911.Default__BP_Magazine_Bolt1911_C",
		},
		["BP_Magazine_Bolt1911_Extended_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_Bolt1911_Extended.Default__BP_Magazine_Bolt1911_Extended_C",
		},
		["BP_Magazine_FiftySeven_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_FiftySeven.Default__BP_Magazine_FiftySeven_C",
		},
		["BP_Magazine_FiftySeven_Extended_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_FiftySeven_Extended.Default__BP_Magazine_FiftySeven_Extended_C",
		},
		["BP_Magazine_Flock17_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_Flock17.Default__BP_Magazine_Flock17_C",
		},
		["BP_Magazine_Flock17_Extended_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_Flock17_Extended.Default__BP_Magazine_Flock17_Extended_C",
		},
		["BP_Magazine_MP5_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_MP5.Default__BP_Magazine_MP5_C",
		},
		["BP_Magazine_N16_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_N16.Default__BP_Magazine_N16_C",
		},
		["BP_Magazine_P9_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Ammo/BP_Magazine_P9.Default__BP_Magazine_P9_C",
		},
}
