-- clothing.lua
return {
		["BP_CL_Apron_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_Apron.Default__BP_CL_Apron_C",
		},
		["BP_CL_ArmoredMotorcyclePants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05b_LowerArmor/BP_CL_ArmoredMotorcyclePants.Default__BP_CL_ArmoredMotorcyclePants_C",
		},
		["BP_CL_BulletproofVestCiv_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_BulletproofVestCiv.Default__BP_CL_BulletproofVestCiv_C",
		},
		["BP_CL_BulletproofVestDeputy_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_BulletproofVestDeputy.Default__BP_CL_BulletproofVestDeputy_C",
		},
		["BP_CL_BulletproofVestMilitary_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_BulletproofVestMilitary.Default__BP_CL_BulletproofVestMilitary_C",
		},
		["BP_CL_BulletproofVestPolice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_BulletproofVestPolice.Default__BP_CL_BulletproofVestPolice_C",
		},
		["BP_CL_BulletproofVestRiot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_BulletproofVestRiot.Default__BP_CL_BulletproofVestRiot_C",
		},
		["BP_CL_BulletproofVestSheriff_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_BulletproofVestSheriff.Default__BP_CL_BulletproofVestSheriff_C",
		},
		["BP_CL_BulletproofVestStateTrooper_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_BulletproofVestStateTrooper.Default__BP_CL_BulletproofVestStateTrooper_C",
		},
		["BP_CL_ChefJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_ChefJacket.Default__BP_CL_ChefJacket_C",
		},
		["BP_CL_ChefPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_ChefPants.Default__BP_CL_ChefPants_C",
		},
		["BP_CL_CorrectionalPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_CorrectionalPants.Default__BP_CL_CorrectionalPants_C",
		},
		["BP_CL_CorrectionalShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_CorrectionalShirt.Default__BP_CL_CorrectionalShirt_C",
		},
		["BP_CL_CropTop_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_CropTop.Default__BP_CL_CropTop_C",
		},
		["BP_CL_DenimJeans_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_DenimJeans.Default__BP_CL_DenimJeans_C",
		},
		["BP_CL_DenimShirtLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_DenimShirtLong.Default__BP_CL_DenimShirtLong_C",
		},
		["BP_CL_DenimShorts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_DenimShorts.Default__BP_CL_DenimShorts_C",
		},
		["BP_CL_DeputyJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_DeputyJacket.Default__BP_CL_DeputyJacket_C",
		},
		["BP_CL_DeputyPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_DeputyPants.Default__BP_CL_DeputyPants_C",
		},
		["BP_CL_DeputyShirtLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_DeputyShirtLong.Default__BP_CL_DeputyShirtLong_C",
		},
		["BP_CL_DoctorsCoat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_DoctorsCoat.Default__BP_CL_DoctorsCoat_C",
		},
		["BP_CL_DoctorsPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_DoctorsPants.Default__BP_CL_DoctorsPants_C",
		},
		["BP_CL_DolphinShorts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_DolphinShorts.Default__BP_CL_DolphinShorts_C",
		},
		["BP_CL_DressLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_DressLong.Default__BP_CL_DressLong_C",
		},
		["BP_CL_DressShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_DressShirt.Default__BP_CL_DressShirt_C",
		},
		["BP_CL_Face_AviatorGlasses_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_AviatorGlasses.Default__BP_CL_Face_AviatorGlasses_C",
		},
		["BP_CL_Face_Bandana_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_Bandana.Default__BP_CL_Face_Bandana_C",
		},
		["BP_CL_Face_ClownNose_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_ClownNose.Default__BP_CL_Face_ClownNose_C",
		},
		["BP_CL_Face_CoolGlasses_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_CoolGlasses.Default__BP_CL_Face_CoolGlasses_C",
		},
		["BP_CL_Face_DustMask_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_DustMask.Default__BP_CL_Face_DustMask_C",
		},
		["BP_CL_Face_Glasses_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_Glasses.Default__BP_CL_Face_Glasses_C",
		},
		["BP_CL_Face_HockeyMask_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_HockeyMask.Default__BP_CL_Face_HockeyMask_C",
		},
		["BP_CL_Face_MedicalMask_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_MedicalMask.Default__BP_CL_Face_MedicalMask_C",
		},
		["BP_CL_Face_PetCollar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_PetCollar.Default__BP_CL_Face_PetCollar_C",
		},
		["BP_CL_Face_ReadingGlasses_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_ReadingGlasses.Default__BP_CL_Face_ReadingGlasses_C",
		},
		["BP_CL_Face_Rebreather_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_Rebreather.Default__BP_CL_Face_Rebreather_C",
		},
		["BP_CL_Face_Respirator_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_Respirator.Default__BP_CL_Face_Respirator_C",
		},
		["BP_CL_Face_RoundGlasses_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_RoundGlasses.Default__BP_CL_Face_RoundGlasses_C",
		},
		["BP_CL_Face_SafetyGoggles_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_SafetyGoggles.Default__BP_CL_Face_SafetyGoggles_C",
		},
		["BP_CL_Face_SkiGoggles_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_SkiGoggles.Default__BP_CL_Face_SkiGoggles_C",
		},
		["BP_CL_Face_SleepingMask_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_SleepingMask.Default__BP_CL_Face_SleepingMask_C",
		},
		["BP_CL_Face_SpaMask_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_SpaMask.Default__BP_CL_Face_SpaMask_C",
		},
		["BP_CL_Face_SwimmingGoggles_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_SwimmingGoggles.Default__BP_CL_Face_SwimmingGoggles_C",
		},
		["BP_CL_Face_WeldingHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/02_Face/BP_CL_Face_WeldingHelmet.Default__BP_CL_Face_WeldingHelmet_C",
		},
		["BP_CL_FirefighterJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_FirefighterJacket.Default__BP_CL_FirefighterJacket_C",
		},
		["BP_CL_FirefighterPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_FirefighterPants.Default__BP_CL_FirefighterPants_C",
		},
		["BP_CL_FootballPads_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_FootballPads.Default__BP_CL_FootballPads_C",
		},
		["BP_CL_GymShorts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_GymShorts.Default__BP_CL_GymShorts_C",
		},
		["BP_CL_Hands_FingerlessGloves_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/07_Hands/BP_CL_Hands_FingerlessGloves.Default__BP_CL_Hands_FingerlessGloves_C",
		},
		["BP_CL_Hands_FirefighterGloves_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/07_Hands/BP_CL_Hands_FirefighterGloves.Default__BP_CL_Hands_FirefighterGloves_C",
		},
		["BP_CL_Hands_GardenGloves_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/07_Hands/BP_CL_Hands_GardenGloves.Default__BP_CL_Hands_GardenGloves_C",
		},
		["BP_CL_Hands_LatexGloves_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/07_Hands/BP_CL_Hands_LatexGloves.Default__BP_CL_Hands_LatexGloves_C",
		},
		["BP_CL_Hands_LeatherGloves_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/07_Hands/BP_CL_Hands_LeatherGloves.Default__BP_CL_Hands_LeatherGloves_C",
		},
		["BP_CL_Hands_WoolGloves_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/07_Hands/BP_CL_Hands_WoolGloves.Default__BP_CL_Hands_WoolGloves_C",
		},
		["BP_CL_HawaiianShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_HawaiianShirt.Default__BP_CL_HawaiianShirt_C",
		},
		["BP_CL_HazmatSuit_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/09_FullBody/BP_CL_HazmatSuit.Default__BP_CL_HazmatSuit_C",
		},
		["BP_CL_Head_Balaclava_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_Balaclava.Default__BP_CL_Head_Balaclava_C",
		},
		["BP_CL_Head_BaseballCap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_BaseballCap.Default__BP_CL_Head_BaseballCap_C",
		},
		["BP_CL_Head_Beanie_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_Beanie.Default__BP_CL_Head_Beanie_C",
		},
		["BP_CL_Head_Beret_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_Beret.Default__BP_CL_Head_Beret_C",
		},
		["BP_CL_Head_BicycleHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_BicycleHelmet.Default__BP_CL_Head_BicycleHelmet_C",
		},
		["BP_CL_Head_Boonie_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_Boonie.Default__BP_CL_Head_Boonie_C",
		},
		["BP_CL_Head_BowlerHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_BowlerHat.Default__BP_CL_Head_BowlerHat_C",
		},
		["BP_CL_Head_BoxingGearHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_BoxingGearHelmet.Default__BP_CL_Head_BoxingGearHelmet_C",
		},
		["BP_CL_Head_BunnyEars_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_BunnyEars.Default__BP_CL_Head_BunnyEars_C",
		},
		["BP_CL_Head_CatEars_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_CatEars.Default__BP_CL_Head_CatEars_C",
		},
		["BP_CL_Head_ChefHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_ChefHat.Default__BP_CL_Head_ChefHat_C",
		},
		["BP_CL_Head_CombatHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_CombatHelmet.Default__BP_CL_Head_CombatHelmet_C",
		},
		["BP_CL_Head_ConstructionHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_ConstructionHelmet.Default__BP_CL_Head_ConstructionHelmet_C",
		},
		["BP_CL_Head_CowboyHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_CowboyHat.Default__BP_CL_Head_CowboyHat_C",
		},
		["BP_CL_Head_DeputyHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_DeputyHat.Default__BP_CL_Head_DeputyHat_C",
		},
		["BP_CL_Head_EarProtectors_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_EarProtectors.Default__BP_CL_Head_EarProtectors_C",
		},
		["BP_CL_Head_Fedora_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_Fedora.Default__BP_CL_Head_Fedora_C",
		},
		["BP_CL_Head_FirefighterHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_FirefighterHelmet.Default__BP_CL_Head_FirefighterHelmet_C",
		},
		["BP_CL_Head_FishingHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_FishingHat.Default__BP_CL_Head_FishingHat_C",
		},
		["BP_CL_Head_FootballHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_FootballHelmet.Default__BP_CL_Head_FootballHelmet_C",
		},
		["BP_CL_Head_GolfVisor_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_GolfVisor.Default__BP_CL_Head_GolfVisor_C",
		},
		["BP_CL_Head_Headband_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_Headband.Default__BP_CL_Head_Headband_C",
		},
		["BP_CL_Head_HeadlightHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_HeadlightHelmet.Default__BP_CL_Head_HeadlightHelmet_C",
		},
		["BP_CL_Head_HeadlightHelmet_Waterproof_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_HeadlightHelmet_Waterproof.Default__BP_CL_Head_HeadlightHelmet_Waterproof_C",
		},
		["BP_CL_Head_HockeyHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_HockeyHelmet.Default__BP_CL_Head_HockeyHelmet_C",
		},
		["BP_CL_Head_MilitaryHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_MilitaryHat.Default__BP_CL_Head_MilitaryHat_C",
		},
		["BP_CL_Head_MotorcycleHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_MotorcycleHelmet.Default__BP_CL_Head_MotorcycleHelmet_C",
		},
		["BP_CL_Head_OpenBalaclava_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_OpenBalaclava.Default__BP_CL_Head_OpenBalaclava_C",
		},
		["BP_CL_Head_PartyHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_PartyHat.Default__BP_CL_Head_PartyHat_C",
		},
		["BP_CL_Head_PoliceHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_PoliceHat.Default__BP_CL_Head_PoliceHat_C",
		},
		["BP_CL_Head_PomPomHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_PomPomHat.Default__BP_CL_Head_PomPomHat_C",
		},
		["BP_CL_Head_Pylon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_Pylon.Default__BP_CL_Head_Pylon_C",
		},
		["BP_CL_Head_RangerHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_RangerHat.Default__BP_CL_Head_RangerHat_C",
		},
		["BP_CL_Head_RiotHelmet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_RiotHelmet.Default__BP_CL_Head_RiotHelmet_C",
		},
		["BP_CL_Head_SheriffHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_SheriffHat.Default__BP_CL_Head_SheriffHat_C",
		},
		["BP_CL_Head_ShowerCap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_ShowerCap.Default__BP_CL_Head_ShowerCap_C",
		},
		["BP_CL_Head_StateTrooperHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_StateTrooperHat.Default__BP_CL_Head_StateTrooperHat_C",
		},
		["BP_CL_Head_StrawHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_StrawHat.Default__BP_CL_Head_StrawHat_C",
		},
		["BP_CL_Head_TinFoilHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_TinFoilHat.Default__BP_CL_Head_TinFoilHat_C",
		},
		["BP_CL_Head_TopHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_TopHat.Default__BP_CL_Head_TopHat_C",
		},
		["BP_CL_Head_TrapperHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_TrapperHat.Default__BP_CL_Head_TrapperHat_C",
		},
		["BP_CL_Head_TruckerHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_TruckerHat.Default__BP_CL_Head_TruckerHat_C",
		},
		["BP_CL_Head_WeddingVeil_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/01_Head/BP_CL_Head_WeddingVeil.Default__BP_CL_Head_WeddingVeil_C",
		},
		["BP_CL_Hoodie_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_Hoodie.Default__BP_CL_Hoodie_C",
		},
		["BP_CL_HuntingVest_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04b_UpperArmor/BP_CL_HuntingVest.Default__BP_CL_HuntingVest_C",
		},
		["BP_CL_JeanJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_JeanJacket.Default__BP_CL_JeanJacket_C",
		},
		["BP_CL_KhakiPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_KhakiPants.Default__BP_CL_KhakiPants_C",
		},
		["BP_CL_KhakiShorts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_KhakiShorts.Default__BP_CL_KhakiShorts_C",
		},
		["BP_CL_Kneepads_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05b_LowerArmor/BP_CL_Kneepads.Default__BP_CL_Kneepads_C",
		},
		["BP_CL_LeatherJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_LeatherJacket.Default__BP_CL_LeatherJacket_C",
		},
		["BP_CL_LifePreserver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_LifePreserver.Default__BP_CL_LifePreserver_C",
		},
		["BP_CL_LongSleeveShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_LongSleeveShirt.Default__BP_CL_LongSleeveShirt_C",
		},
		["BP_CL_MaplemartTShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_MaplemartTShirt.Default__BP_CL_MaplemartTShirt_C",
		},
		["BP_CL_MedicalScrubsLower_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_MedicalScrubsLower.Default__BP_CL_MedicalScrubsLower_C",
		},
		["BP_CL_MedicalScrubsTop_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_MedicalScrubsTop.Default__BP_CL_MedicalScrubsTop_C",
		},
		["BP_CL_MilitaryJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_MilitaryJacket.Default__BP_CL_MilitaryJacket_C",
		},
		["BP_CL_MilitaryPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_MilitaryPants.Default__BP_CL_MilitaryPants_C",
		},
		["BP_CL_MilitaryTop_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_MilitaryTop.Default__BP_CL_MilitaryTop_C",
		},
		["BP_CL_OffShoulderShirtLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_OffShoulderShirtLong.Default__BP_CL_OffShoulderShirtLong_C",
		},
		["BP_CL_Overalls_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_Overalls.Default__BP_CL_Overalls_C",
		},
		["BP_CL_OversizedSweater_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_OversizedSweater.Default__BP_CL_OversizedSweater_C",
		},
		["BP_CL_PlaidShirtLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_PlaidShirtLong.Default__BP_CL_PlaidShirtLong_C",
		},
		["BP_CL_PolicePants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_PolicePants.Default__BP_CL_PolicePants_C",
		},
		["BP_CL_PoliceShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_PoliceShirt.Default__BP_CL_PoliceShirt_C",
		},
		["BP_CL_Polo_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_Polo.Default__BP_CL_Polo_C",
		},
		["BP_CL_PrisonGuardPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_PrisonGuardPants.Default__BP_CL_PrisonGuardPants_C",
		},
		["BP_CL_PrisonJumpsuit_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/09_FullBody/BP_CL_PrisonJumpsuit.Default__BP_CL_PrisonJumpsuit_C",
		},
		["BP_CL_PufferJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_PufferJacket.Default__BP_CL_PufferJacket_C",
		},
		["BP_CL_RainCoat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_RainCoat.Default__BP_CL_RainCoat_C",
		},
		["BP_CL_RamjetStudiosTShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_RamjetStudiosTShirt.Default__BP_CL_RamjetStudiosTShirt_C",
		},
		["BP_CL_RangerJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_RangerJacket.Default__BP_CL_RangerJacket_C",
		},
		["BP_CL_RangerPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_RangerPants.Default__BP_CL_RangerPants_C",
		},
		["BP_CL_RangerShirtLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_RangerShirtLong.Default__BP_CL_RangerShirtLong_C",
		},
		["BP_CL_RiotPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_RiotPants.Default__BP_CL_RiotPants_C",
		},
		["BP_CL_RiotShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_RiotShirt.Default__BP_CL_RiotShirt_C",
		},
		["BP_CL_SafetyVest_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_SafetyVest.Default__BP_CL_SafetyVest_C",
		},
		["BP_CL_SheriffJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_SheriffJacket.Default__BP_CL_SheriffJacket_C",
		},
		["BP_CL_SheriffPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_SheriffPants.Default__BP_CL_SheriffPants_C",
		},
		["BP_CL_SheriffShirtLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_SheriffShirtLong.Default__BP_CL_SheriffShirtLong_C",
		},
		["BP_CL_Shoes_Boots_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Boots.Default__BP_CL_Shoes_Boots_C",
		},
		["BP_CL_Shoes_BowlingShoes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_BowlingShoes.Default__BP_CL_Shoes_BowlingShoes_C",
		},
		["BP_CL_Shoes_BunnySlippers_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_BunnySlippers.Default__BP_CL_Shoes_BunnySlippers_C",
		},
		["BP_CL_Shoes_Correctional_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Correctional.Default__BP_CL_Shoes_Correctional_C",
		},
		["BP_CL_Shoes_Dress_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Dress.Default__BP_CL_Shoes_Dress_C",
		},
		["BP_CL_Shoes_FirefighterBoots_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_FirefighterBoots.Default__BP_CL_Shoes_FirefighterBoots_C",
		},
		["BP_CL_Shoes_FlipFlops_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_FlipFlops.Default__BP_CL_Shoes_FlipFlops_C",
		},
		["BP_CL_Shoes_GothBoots_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_GothBoots.Default__BP_CL_Shoes_GothBoots_C",
		},
		["BP_CL_Shoes_Heels_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Heels.Default__BP_CL_Shoes_Heels_C",
		},
		["BP_CL_Shoes_Leather_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Leather.Default__BP_CL_Shoes_Leather_C",
		},
		["BP_CL_Shoes_MilitaryBoots_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_MilitaryBoots.Default__BP_CL_Shoes_MilitaryBoots_C",
		},
		["BP_CL_Shoes_Phoenix1s_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Phoenix1s.Default__BP_CL_Shoes_Phoenix1s_C",
		},
		["BP_CL_Shoes_Police_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Police.Default__BP_CL_Shoes_Police_C",
		},
		["BP_CL_Shoes_RainBoots_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_RainBoots.Default__BP_CL_Shoes_RainBoots_C",
		},
		["BP_CL_Shoes_Rollerblades_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Rollerblades.Default__BP_CL_Shoes_Rollerblades_C",
		},
		["BP_CL_Shoes_Sandals_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Sandals.Default__BP_CL_Shoes_Sandals_C",
		},
		["BP_CL_Shoes_Sneakers_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/06_Feet/BP_CL_Shoes_Sneakers.Default__BP_CL_Shoes_Sneakers_C",
		},
		["BP_CL_SkinnyJeans_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_SkinnyJeans.Default__BP_CL_SkinnyJeans_C",
		},
		["BP_CL_Skirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_Skirt.Default__BP_CL_Skirt_C",
		},
		["BP_CL_SkirtLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_SkirtLong.Default__BP_CL_SkirtLong_C",
		},
		["BP_CL_SnowPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_SnowPants.Default__BP_CL_SnowPants_C",
		},
		["BP_CL_StateTrooperJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_StateTrooperJacket.Default__BP_CL_StateTrooperJacket_C",
		},
		["BP_CL_StateTrooperPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_StateTrooperPants.Default__BP_CL_StateTrooperPants_C",
		},
		["BP_CL_StateTrooperShirtLong_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_StateTrooperShirtLong.Default__BP_CL_StateTrooperShirtLong_C",
		},
		["BP_CL_SuitJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_SuitJacket.Default__BP_CL_SuitJacket_C",
		},
		["BP_CL_SuitPants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_SuitPants.Default__BP_CL_SuitPants_C",
		},
		["BP_CL_Sweater_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_Sweater.Default__BP_CL_Sweater_C",
		},
		["BP_CL_SweaterVest_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_SweaterVest.Default__BP_CL_SweaterVest_C",
		},
		["BP_CL_Sweatpants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/05a_Lower/BP_CL_Sweatpants.Default__BP_CL_Sweatpants_C",
		},
		["BP_CL_TankTop_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_TankTop.Default__BP_CL_TankTop_C",
		},
		["BP_CL_TrenchCoat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_TrenchCoat.Default__BP_CL_TrenchCoat_C",
		},
		["BP_CL_TShirt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/04a_Upper/BP_CL_TShirt.Default__BP_CL_TShirt_C",
		},
		["BP_CL_Tuxedo_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_Tuxedo.Default__BP_CL_Tuxedo_C",
		},
		["BP_CL_VarsityJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_VarsityJacket.Default__BP_CL_VarsityJacket_C",
		},
		["BP_CL_WinterJacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/03_Jacket/BP_CL_WinterJacket.Default__BP_CL_WinterJacket_C",
		},
		["BP_PortableAirTank_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Clothing/08_Back/BP_PortableAirTank.Default__BP_PortableAirTank_C",
		},
}
