-- consumables.lua
return {
		["BP_AgedCheese_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_AgedCheese.Default__BP_AgedCheese_C",
		},
		["BP_Alewife_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Herrings/BP_Alewife.Default__BP_Alewife_C",
		},
		["BP_AlleghenyPearlDace_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_AlleghenyPearlDace.Default__BP_AlleghenyPearlDace_C",
		},
		["BP_AmericanBrookLamprey_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Lampreys/BP_AmericanBrookLamprey.Default__BP_AmericanBrookLamprey_C",
		},
		["BP_AmericanBullfrog_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Amphibians/Frogs/BP_AmericanBullfrog.Default__BP_AmericanBullfrog_C",
		},
		["BP_AmericanEel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/FreshwaterEels/BP_AmericanEel.Default__BP_AmericanEel_C",
		},
		["BP_Apple_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Apple.Default__BP_Apple_C",
		},
		["BP_AppleSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_AppleSlice.Default__BP_AppleSlice_C",
		},
		["BP_Artichoke_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Artichoke.Default__BP_Artichoke_C",
		},
		["BP_ArtichokeHalf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_ArtichokeHalf.Default__BP_ArtichokeHalf_C",
		},
		["BP_AtlanticSalmon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_AtlanticSalmon.Default__BP_AtlanticSalmon_C",
		},
		["BP_Avocado_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Avocado.Default__BP_Avocado_C",
		},
		["BP_AvocadoHalf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_AvocadoHalf.Default__BP_AvocadoHalf_C",
		},
		["BP_BabyOil_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Cleaning/BP_BabyOil.Default__BP_BabyOil_C",
		},
		["BP_Bacon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Bacon.Default__BP_Bacon_C",
		},
		["BP_Bagel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Bagel.Default__BP_Bagel_C",
		},
		["BP_Baguette_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Baguette.Default__BP_Baguette_C",
		},
		["BP_Banana_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Banana.Default__BP_Banana_C",
		},
		["BP_BandedKillifish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Topminnows/BP_BandedKillifish.Default__BP_BandedKillifish_C",
		},
		["BP_BandedSculpin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sculpins/BP_BandedSculpin.Default__BP_BandedSculpin_C",
		},
		["BP_BarberSterilizingJar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_BarberSterilizingJar.Default__BP_BarberSterilizingJar_C",
		},
		["BP_BaseFish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/BP_BaseFish.Default__BP_BaseFish_C",
		},
		["BP_BBQFajita_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_BBQFajita.Default__BP_BBQFajita_C",
		},
		["BP_Beef_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Beef.Default__BP_Beef_C",
		},
		["BP_BeefStew_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_BeefStew.Default__BP_BeefStew_C",
		},
		["BP_BeefWellington_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_BeefWellington.Default__BP_BeefWellington_C",
		},
		["BP_BeerBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_BeerBottle.Default__BP_BeerBottle_C",
		},
		["BP_BeerKeg_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_BeerKeg.Default__BP_BeerKeg_C",
		},
		["BP_Bird_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Bird.Default__BP_Bird_C",
		},
		["BP_BirdMeat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_BirdMeat.Default__BP_BirdMeat_C",
		},
		["BP_BiscuitBox01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BiscuitBox01.Default__BP_BiscuitBox01_C",
		},
		["BP_BlackBullhead_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Catfishes/BP_BlackBullhead.Default__BP_BlackBullhead_C",
		},
		["BP_BlackchinShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_BlackchinShiner.Default__BP_BlackchinShiner_C",
		},
		["BP_BlackCrappie_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sunfishes/BP_BlackCrappie.Default__BP_BlackCrappie_C",
		},
		["BP_BlackGarlic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_BlackGarlic.Default__BP_BlackGarlic_C",
		},
		["BP_BlacknoseShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_BlacknoseShiner.Default__BP_BlacknoseShiner_C",
		},
		["BP_BleachBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_BleachBottle.Default__BP_BleachBottle_C",
		},
		["BP_BloodSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_BloodSoup.Default__BP_BloodSoup_C",
		},
		["BP_BluebackHerring_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Herrings/BP_BluebackHerring.Default__BP_BluebackHerring_C",
		},
		["BP_Bluegill_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sunfishes/BP_Bluegill.Default__BP_Bluegill_C",
		},
		["BP_Blue-SpottedSalamander_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Amphibians/Salamanders/BP_Blue-SpottedSalamander.Default__BP_Blue-SpottedSalamander_C",
		},
		["BP_BluntnoseMinnow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_BluntnoseMinnow.Default__BP_BluntnoseMinnow_C",
		},
		["BP_BonitoFlakes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_BonitoFlakes.Default__BP_BonitoFlakes_C",
		},
		["BP_Bowfin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Bowfin/BP_Bowfin.Default__BP_Bowfin_C",
		},
		["BP_BoxedBoomTarts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedBoomTarts.Default__BP_BoxedBoomTarts_C",
		},
		["BP_BoxedBreadsticks_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedBreadsticks.Default__BP_BoxedBreadsticks_C",
		},
		["BP_BoxedCitrusCakes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedCitrusCakes.Default__BP_BoxedCitrusCakes_C",
		},
		["BP_BoxedCookies_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedCookies.Default__BP_BoxedCookies_C",
		},
		["BP_BoxedCrackers01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedCrackers01.Default__BP_BoxedCrackers01_C",
		},
		["BP_BoxedCrackers02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedCrackers02.Default__BP_BoxedCrackers02_C",
		},
		["BP_BoxedEnchilada_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedEnchilada.Default__BP_BoxedEnchilada_C",
		},
		["BP_BoxedFajitaBBQ_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedFajitaBBQ.Default__BP_BoxedFajitaBBQ_C",
		},
		["BP_BoxedFajitaChicken_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedFajitaChicken.Default__BP_BoxedFajitaChicken_C",
		},
		["BP_BoxedFruitGranola_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedFruitGranola.Default__BP_BoxedFruitGranola_C",
		},
		["BP_BoxedHazelnutCookies_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedHazelnutCookies.Default__BP_BoxedHazelnutCookies_C",
		},
		["BP_BoxedMacCheese_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedMacCheese.Default__BP_BoxedMacCheese_C",
		},
		["BP_BoxedNoodles_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedNoodles.Default__BP_BoxedNoodles_C",
		},
		["BP_BoxedOatmealApple_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedOatmealApple.Default__BP_BoxedOatmealApple_C",
		},
		["BP_BoxedOatmealMaple_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedOatmealMaple.Default__BP_BoxedOatmealMaple_C",
		},
		["BP_BoxedOatmealOriginal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedOatmealOriginal.Default__BP_BoxedOatmealOriginal_C",
		},
		["BP_BoxedTortilla_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedTortilla.Default__BP_BoxedTortilla_C",
		},
		["BP_BoxedWheatBiscuits_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_BoxedWheatBiscuits.Default__BP_BoxedWheatBiscuits_C",
		},
		["BP_BrassyMinnow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_BrassyMinnow.Default__BP_BrassyMinnow_C",
		},
		["BP_BreadLoaf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_BreadLoaf.Default__BP_BreadLoaf_C",
		},
		["BP_BreadSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_BreadSlice.Default__BP_BreadSlice_C",
		},
		["BP_BridleShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_BridleShiner.Default__BP_BridleShiner_C",
		},
		["BP_Broccoli_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Broccoli.Default__BP_Broccoli_C",
		},
		["BP_BrookSilverside_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/NewWorldSilversides/BP_BrookSilverside.Default__BP_BrookSilverside_C",
		},
		["BP_BrookStickleback_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sticklebacks/BP_BrookStickleback.Default__BP_BrookStickleback_C",
		},
		["BP_BrookTrout_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_BrookTrout.Default__BP_BrookTrout_C",
		},
		["BP_BrothBeef_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Pantry/BP_BrothBeef.Default__BP_BrothBeef_C",
		},
		["BP_BrothChicken_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Pantry/BP_BrothChicken.Default__BP_BrothChicken_C",
		},
		["BP_BrothVegetable_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Pantry/BP_BrothVegetable.Default__BP_BrothVegetable_C",
		},
		["BP_BrownBullhead_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Catfishes/BP_BrownBullhead.Default__BP_BrownBullhead_C",
		},
		["BP_Brownie_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Brownie.Default__BP_Brownie_C",
		},
		["BP_BrownTrout_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_BrownTrout.Default__BP_BrownTrout_C",
		},
		["BP_BunnyFeed_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Outdoors/BP_BunnyFeed.Default__BP_BunnyFeed_C",
		},
		["BP_Burbot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Cods/BP_Burbot.Default__BP_Burbot_C",
		},
		["BP_Butter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_Butter.Default__BP_Butter_C",
		},
		["BP_Cabbage_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Cabbage.Default__BP_Cabbage_C",
		},
		["BP_Cake01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Cake01.Default__BP_Cake01_C",
		},
		["BP_Candy01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_Candy01.Default__BP_Candy01_C",
		},
		["BP_Candy02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_Candy02.Default__BP_Candy02_C",
		},
		["BP_Cannabis_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Drugs/BP_Cannabis.Default__BP_Cannabis_C",
		},
		["BP_CannedBeanSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedBeanSoup.Default__BP_CannedBeanSoup_C",
		},
		["BP_CannedChickenNoodleSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedChickenNoodleSoup.Default__BP_CannedChickenNoodleSoup_C",
		},
		["BP_CannedCorn_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedCorn.Default__BP_CannedCorn_C",
		},
		["BP_CannedCreamChickenSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedCreamChickenSoup.Default__BP_CannedCreamChickenSoup_C",
		},
		["BP_CannedHerring_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedHerring.Default__BP_CannedHerring_C",
		},
		["BP_CannedPeas_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedPeas.Default__BP_CannedPeas_C",
		},
		["BP_CannedTomatoes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedTomatoes.Default__BP_CannedTomatoes_C",
		},
		["BP_CannedTuna_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedTuna.Default__BP_CannedTuna_C",
		},
		["BP_CannedVegetableSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CannedVegetableSoup.Default__BP_CannedVegetableSoup_C",
		},
		["BP_Cantaloupe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Cantaloupe.Default__BP_Cantaloupe_C",
		},
		["BP_CantaloupeSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_CantaloupeSlice.Default__BP_CantaloupeSlice_C",
		},
		["BP_Canteen_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_Canteen.Default__BP_Canteen_C",
		},
		["BP_CaramelizedHazelnutSteak_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_CaramelizedHazelnutSteak.Default__BP_CaramelizedHazelnutSteak_C",
		},
		["BP_CarOilBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Car/BP_CarOilBottle.Default__BP_CarOilBottle_C",
		},
		["BP_Carrot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Carrot.Default__BP_Carrot_C",
		},
		["BP_CarrotSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_CarrotSlice.Default__BP_CarrotSlice_C",
		},
		["BP_CarrotSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_CarrotSoup.Default__BP_CarrotSoup_C",
		},
		["BP_CatFood_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CatFood.Default__BP_CatFood_C",
		},
		["BP_CatFoodWet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CatFoodWet.Default__BP_CatFoodWet_C",
		},
		["BP_Cauliflower_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Cauliflower.Default__BP_Cauliflower_C",
		},
		["BP_CaveLeech_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Other/BP_CaveLeech.Default__BP_CaveLeech_C",
		},
		["BP_Caviar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_Caviar.Default__BP_Caviar_C",
		},
		["BP_CaviarSauceScallops_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_CaviarSauceScallops.Default__BP_CaviarSauceScallops_C",
		},
		["BP_CentralMudminnow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/PikeMudminnows/BP_CentralMudminnow.Default__BP_CentralMudminnow_C",
		},
		["BP_CerealBox_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CerealBox.Default__BP_CerealBox_C",
		},
		["BP_ChainPickerel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/PikeMudminnows/BP_ChainPickerel.Default__BP_ChainPickerel_C",
		},
		["BP_ChannelCatfish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Catfishes/BP_ChannelCatfish.Default__BP_ChannelCatfish_C",
		},
		["BP_ChannelDarter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_ChannelDarter.Default__BP_ChannelDarter_C",
		},
		["BP_Cheese_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_Cheese.Default__BP_Cheese_C",
		},
		["BP_CheeseFondue_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_CheeseFondue.Default__BP_CheeseFondue_C",
		},
		["BP_Chicken_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Chicken.Default__BP_Chicken_C",
		},
		["BP_ChickenCasserole_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/OvenDish/BP_ChickenCasserole.Default__BP_ChickenCasserole_C",
		},
		["BP_ChickenFajita_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_ChickenFajita.Default__BP_ChickenFajita_C",
		},
		["BP_ChickenFeed_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Outdoors/BP_ChickenFeed.Default__BP_ChickenFeed_C",
		},
		["BP_ChickenParmesan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/OvenDish/BP_ChickenParmesan.Default__BP_ChickenParmesan_C",
		},
		["BP_ChipBag01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_ChipBag01.Default__BP_ChipBag01_C",
		},
		["BP_ChipBag02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_ChipBag02.Default__BP_ChipBag02_C",
		},
		["BP_ChipBag03_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_ChipBag03.Default__BP_ChipBag03_C",
		},
		["BP_ChipBag04_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_ChipBag04.Default__BP_ChipBag04_C",
		},
		["BP_ChocolateFondue_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_ChocolateFondue.Default__BP_ChocolateFondue_C",
		},
		["BP_Cigarettes01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Drugs/BP_Cigarettes01.Default__BP_Cigarettes01_C",
		},
		["BP_Cisco_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_Cisco.Default__BP_Cisco_C",
		},
		["BP_ClassicEscargot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_ClassicEscargot.Default__BP_ClassicEscargot_C",
		},
		["BP_CleanerCasserole_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Poisons/BP_CleanerCasserole.Default__BP_CleanerCasserole_C",
		},
		["BP_Cocaine_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Drugs/BP_Cocaine.Default__BP_Cocaine_C",
		},
		["BP_Coconut_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Coconut.Default__BP_Coconut_C",
		},
		["BP_CoffeeBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CoffeeBag.Default__BP_CoffeeBag_C",
		},
		["BP_ColdMedicine_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Drugs/BP_ColdMedicine.Default__BP_ColdMedicine_C",
		},
		["BP_ComicBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Literature/BP_ComicBook.Default__BP_ComicBook_C",
		},
		["BP_CommonCarp_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_CommonCarp.Default__BP_CommonCarp_C",
		},
		["BP_CommonMullein_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_CommonMullein.Default__BP_CommonMullein_C",
		},
		["BP_CommonShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_CommonShiner.Default__BP_CommonShiner_C",
		},
		["BP_Cookie01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Cookie01.Default__BP_Cookie01_C",
		},
		["BP_Cookie02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Cookie02.Default__BP_Cookie02_C",
		},
		["BP_CookingOil_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Pantry/BP_CookingOil.Default__BP_CookingOil_C",
		},
		["BP_Corn_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Corn.Default__BP_Corn_C",
		},
		["BP_CornSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_CornSoup.Default__BP_CornSoup_C",
		},
		["BP_CowFeed_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Outdoors/BP_CowFeed.Default__BP_CowFeed_C",
		},
		["BP_CreamCheese_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_CreamCheese.Default__BP_CreamCheese_C",
		},
		["BP_CreekChub_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_CreekChub.Default__BP_CreekChub_C",
		},
		["BP_Croissant_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Croissant.Default__BP_Croissant_C",
		},
		["BP_Cucumber_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Cucumber.Default__BP_Cucumber_C",
		},
		["BP_CucumberSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_CucumberSlice.Default__BP_CucumberSlice_C",
		},
		["BP_CutlipMinnow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_CutlipMinnow.Default__BP_CutlipMinnow_C",
		},
		["BP_DeadRat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_DeadRat.Default__BP_DeadRat_C",
		},
		["BP_DeerMeat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_DeerMeat.Default__BP_DeerMeat_C",
		},
		["BP_Detergent01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_Detergent01.Default__BP_Detergent01_C",
		},
		["BP_DicedOctopus_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Rich/BP_DicedOctopus.Default__BP_DicedOctopus_C",
		},
		["BP_DogFood_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_DogFood.Default__BP_DogFood_C",
		},
		["BP_DogFoodWet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_DogFoodWet.Default__BP_DogFoodWet_C",
		},
		["BP_Donut01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Donut01.Default__BP_Donut01_C",
		},
		["BP_Donut02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Donut02.Default__BP_Donut02_C",
		},
		["BP_DriedSeaweed_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_DriedSeaweed.Default__BP_DriedSeaweed_C",
		},
		["BP_DuckEggCustard_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_DuckEggCustard.Default__BP_DuckEggCustard_C",
		},
		["BP_DuckEggs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_DuckEggs.Default__BP_DuckEggs_C",
		},
		["BP_EasternBlacknoseDace_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_EasternBlacknoseDace.Default__BP_EasternBlacknoseDace_C",
		},
		["BP_EasternRed-backedSalamander_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Amphibians/Salamanders/BP_EasternRed-backedSalamander.Default__BP_EasternRed-backedSalamander_C",
		},
		["BP_EasternSandDarter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_EasternSandDarter.Default__BP_EasternSandDarter_C",
		},
		["BP_EasternSilveryMinnow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_EasternSilveryMinnow.Default__BP_EasternSilveryMinnow_C",
		},
		["BP_EdibleGold_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_EdibleGold.Default__BP_EdibleGold_C",
		},
		["BP_EggDropSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_EggDropSoup.Default__BP_EggDropSoup_C",
		},
		["BP_Eggplant_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Eggplant.Default__BP_Eggplant_C",
		},
		["BP_Eggs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_Eggs.Default__BP_Eggs_C",
		},
		["BP_EmeraldShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_EmeraldShiner.Default__BP_EmeraldShiner_C",
		},
		["BP_Enchilada_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_Enchilada.Default__BP_Enchilada_C",
		},
		["BP_EnergyDrinkCan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_EnergyDrinkCan.Default__BP_EnergyDrinkCan_C",
		},
		["BP_Escargot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Rich/BP_Escargot.Default__BP_Escargot_C",
		},
		["BP_ExplosiveCake_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_ExplosiveCake.Default__BP_ExplosiveCake_C",
		},
		["BP_FabricSoftener_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_FabricSoftener.Default__BP_FabricSoftener_C",
		},
		["BP_Fallfish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_Fallfish.Default__BP_Fallfish_C",
		},
		["BP_FancyChocolate01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_FancyChocolate01.Default__BP_FancyChocolate01_C",
		},
		["BP_FancyChocolate02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_FancyChocolate02.Default__BP_FancyChocolate02_C",
		},
		["BP_FancyChocolate03_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_FancyChocolate03.Default__BP_FancyChocolate03_C",
		},
		["BP_FancyHimalayanSalt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_FancyHimalayanSalt.Default__BP_FancyHimalayanSalt_C",
		},
		["BP_FantailDarter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_FantailDarter.Default__BP_FantailDarter_C",
		},
		["BP_FatheadMinnow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_FatheadMinnow.Default__BP_FatheadMinnow_C",
		},
		["BP_FinescaleDace_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_FinescaleDace.Default__BP_FinescaleDace_C",
		},
		["BP_FishChowder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_FishChowder.Default__BP_FishChowder_C",
		},
		["BP_FlourBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_FlourBag.Default__BP_FlourBag_C",
		},
		["BP_FoieGras_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Rich/BP_FoieGras.Default__BP_FoieGras_C",
		},
		["BP_FoieGrasTempuraBites_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_FoieGrasTempuraBites.Default__BP_FoieGrasTempuraBites_C",
		},
		["BP_Four-toedSalamander_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Amphibians/Salamanders/BP_Four-toedSalamander.Default__BP_Four-toedSalamander_C",
		},
		["BP_FoxMeat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_FoxMeat.Default__BP_FoxMeat_C",
		},
		["BP_FreshwaterDrum_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Drums/BP_FreshwaterDrum.Default__BP_FreshwaterDrum_C",
		},
		["BP_FriedRice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_FriedRice.Default__BP_FriedRice_C",
		},
		["BP_FrozenBeefPatties_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_FrozenBeefPatties.Default__BP_FrozenBeefPatties_C",
		},
		["BP_FrozenFish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_FrozenFish.Default__BP_FrozenFish_C",
		},
		["BP_FrozenFries_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_FrozenFries.Default__BP_FrozenFries_C",
		},
		["BP_FrozenWaffles_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_FrozenWaffles.Default__BP_FrozenWaffles_C",
		},
		["BP_Garlic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Garlic.Default__BP_Garlic_C",
		},
		["BP_GiantHogweed_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_GiantHogweed.Default__BP_GiantHogweed_C",
		},
		["BP_GinBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_GinBottle.Default__BP_GinBottle_C",
		},
		["BP_GizzardShad_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Herrings/BP_GizzardShad.Default__BP_GizzardShad_C",
		},
		["BP_GlassCleaner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_GlassCleaner.Default__BP_GlassCleaner_C",
		},
		["BP_GoldenShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_GoldenShiner.Default__BP_GoldenShiner_C",
		},
		["BP_Goldfish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_Goldfish.Default__BP_Goldfish_C",
		},
		["BP_GoldNeedle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Outdoors/BP_GoldNeedle.Default__BP_GoldNeedle_C",
		},
		["BP_GreaterRedhorse_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Suckers/BP_GreaterRedhorse.Default__BP_GreaterRedhorse_C",
		},
		["BP_GreenFrog_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Amphibians/Frogs/BP_GreenFrog.Default__BP_GreenFrog_C",
		},
		["BP_GrilledCheese_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_GrilledCheese.Default__BP_GrilledCheese_C",
		},
		["BP_GrilledFish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_GrilledFish.Default__BP_GrilledFish_C",
		},
		["BP_GrilledPBJ_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_GrilledPBJ.Default__BP_GrilledPBJ_C",
		},
		["BP_GroundCommonMullein_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Grounded/BP_GroundCommonMullein.Default__BP_GroundCommonMullein_C",
		},
		["BP_GroundGiantHogweed_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Grounded/BP_GroundGiantHogweed.Default__BP_GroundGiantHogweed_C",
		},
		["BP_GroundKingBoletus_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Grounded/BP_GroundKingBoletus.Default__BP_GroundKingBoletus_C",
		},
		["BP_GroundMugwort_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Grounded/BP_GroundMugwort.Default__BP_GroundMugwort_C",
		},
		["BP_GroundPurpleConeflower_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Grounded/BP_GroundPurpleConeflower.Default__BP_GroundPurpleConeflower_C",
		},
		["BP_GroundSage_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Grounded/BP_GroundSage.Default__BP_GroundSage_C",
		},
		["BP_GroundWitchsHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Grounded/BP_GroundWitchsHat.Default__BP_GroundWitchsHat_C",
		},
		["BP_GrowthSerum_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_GrowthSerum.Default__BP_GrowthSerum_C",
		},
		["BP_HairDye_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Appearance/BP_HairDye.Default__BP_HairDye_C",
		},
		["BP_HandSoap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_HandSoap.Default__BP_HandSoap_C",
		},
		["BP_HayBundle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Outdoors/BP_HayBundle.Default__BP_HayBundle_C",
		},
		["BP_HazelnutSpread_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_HazelnutSpread.Default__BP_HazelnutSpread_C",
		},
		["BP_Heart_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Heart.Default__BP_Heart_C",
		},
		["BP_HomemadeMarmalade_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_HomemadeMarmalade.Default__BP_HomemadeMarmalade_C",
		},
		["BP_HomestyleMacnCheese_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/OvenDish/BP_HomestyleMacnCheese.Default__BP_HomestyleMacnCheese_C",
		},
		["BP_HotChocolateMix_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_HotChocolateMix.Default__BP_HotChocolateMix_C",
		},
		["BP_HotDogBuns_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_HotDogBuns.Default__BP_HotDogBuns_C",
		},
		["BP_HotDogs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_HotDogs.Default__BP_HotDogs_C",
		},
		["BP_HotSauceBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Pantry/BP_HotSauceBottle.Default__BP_HotSauceBottle_C",
		},
		["BP_HumanFlesh_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_HumanFlesh.Default__BP_HumanFlesh_C",
		},
		["BP_Icecream_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_Icecream.Default__BP_Icecream_C",
		},
		["BP_InsulatedCanteen_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_InsulatedCanteen.Default__BP_InsulatedCanteen_C",
		},
		["BP_InsulatedFlask_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_InsulatedFlask.Default__BP_InsulatedFlask_C",
		},
		["BP_Intestines_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Intestines.Default__BP_Intestines_C",
		},
		["BP_IowaDarter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_IowaDarter.Default__BP_IowaDarter_C",
		},
		["BP_Jambalaya_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_Jambalaya.Default__BP_Jambalaya_C",
		},
		["BP_JamOrange_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_JamOrange.Default__BP_JamOrange_C",
		},
		["BP_JamStrawberry_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_JamStrawberry.Default__BP_JamStrawberry_C",
		},
		["BP_JapaneseMayonaise_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_JapaneseMayonaise.Default__BP_JapaneseMayonaise_C",
		},
		["BP_JuiceCarton_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_JuiceCarton.Default__BP_JuiceCarton_C",
		},
		["BP_JuiceCarton_Small_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_JuiceCarton_Small.Default__BP_JuiceCarton_Small_C",
		},
		["BP_KetchupBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Pantry/BP_KetchupBottle.Default__BP_KetchupBottle_C",
		},
		["BP_KingBoletus_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_KingBoletus.Default__BP_KingBoletus_C",
		},
		["BP_KingBoletusSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Refined/BP_KingBoletusSoup.Default__BP_KingBoletusSoup_C",
		},
		["BP_Knitbone_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_Knitbone.Default__BP_Knitbone_C",
		},
		["BP_KnitboneSalve_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Refined/BP_KnitboneSalve.Default__BP_KnitboneSalve_C",
		},
		["BP_LakeChub_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_LakeChub.Default__BP_LakeChub_C",
		},
		["BP_LakeSturgeon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sturgeons/BP_LakeSturgeon.Default__BP_LakeSturgeon_C",
		},
		["BP_LakeTrout_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_LakeTrout.Default__BP_LakeTrout_C",
		},
		["BP_LakeWhitefish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_LakeWhitefish.Default__BP_LakeWhitefish_C",
		},
		["BP_LargeChocolateMilkJug_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_LargeChocolateMilkJug.Default__BP_LargeChocolateMilkJug_C",
		},
		["BP_LargeJuiceJug_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_LargeJuiceJug.Default__BP_LargeJuiceJug_C",
		},
		["BP_LargeMilkJug_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_LargeMilkJug.Default__BP_LargeMilkJug_C",
		},
		["BP_LargemouthBass_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sunfishes/BP_LargemouthBass.Default__BP_LargemouthBass_C",
		},
		["BP_LargeSodaBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_LargeSodaBottle.Default__BP_LargeSodaBottle_C",
		},
		["BP_LargeWaterBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_LargeWaterBottle.Default__BP_LargeWaterBottle_C",
		},
		["BP_Latkes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_Latkes.Default__BP_Latkes_C",
		},
		["BP_Lemon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Lemon.Default__BP_Lemon_C",
		},
		["BP_LemonSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_LemonSlice.Default__BP_LemonSlice_C",
		},
		["BP_Lime_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Lime.Default__BP_Lime_C",
		},
		["BP_LimeSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_LimeSlice.Default__BP_LimeSlice_C",
		},
		["BP_Liver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Liver.Default__BP_Liver_C",
		},
		["BP_Lobster_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Rich/BP_Lobster.Default__BP_Lobster_C",
		},
		["BP_Logperch_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_Logperch.Default__BP_Logperch_C",
		},
		["BP_LongnoseDace_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_LongnoseDace.Default__BP_LongnoseDace_C",
		},
		["BP_LongnoseGar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Gars/BP_LongnoseGar.Default__BP_LongnoseGar_C",
		},
		["BP_LongnoseSucker_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Suckers/BP_LongnoseSucker.Default__BP_LongnoseSucker_C",
		},
		["BP_LSD_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Drugs/BP_LSD.Default__BP_LSD_C",
		},
		["BP_Macrobdelladecora_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Other/BP_Macrobdelladecora.Default__BP_Macrobdelladecora_C",
		},
		["BP_MadagascarVanillaExtract_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_MadagascarVanillaExtract.Default__BP_MadagascarVanillaExtract_C",
		},
		["BP_Mandarin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Mandarin.Default__BP_Mandarin_C",
		},
		["BP_MandarinWedge_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_MandarinWedge.Default__BP_MandarinWedge_C",
		},
		["BP_Mango_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Mango.Default__BP_Mango_C",
		},
		["BP_MangoHalf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_MangoHalf.Default__BP_MangoHalf_C",
		},
		["BP_ManukaHoney_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_ManukaHoney.Default__BP_ManukaHoney_C",
		},
		["BP_MapleSapBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_MapleSapBottle.Default__BP_MapleSapBottle_C",
		},
		["BP_MapleSyrupBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_MapleSyrupBottle.Default__BP_MapleSyrupBottle_C",
		},
		["BP_Marshmallow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_Marshmallow.Default__BP_Marshmallow_C",
		},
		["BP_MayoJar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_MayoJar.Default__BP_MayoJar_C",
		},
		["BP_Meth_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Drugs/BP_Meth.Default__BP_Meth_C",
		},
		["BP_Michigan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_Michigan.Default__BP_Michigan_C",
		},
		["BP_MichiganSauce_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_MichiganSauce.Default__BP_MichiganSauce_C",
		},
		["BP_MilkCarton_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_MilkCarton.Default__BP_MilkCarton_C",
		},
		["BP_MilkCarton_Small_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_MilkCarton_Small.Default__BP_MilkCarton_Small_C",
		},
		["BP_MilkChocolateCarton_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_MilkChocolateCarton.Default__BP_MilkChocolateCarton_C",
		},
		["BP_MimicShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_MimicShiner.Default__BP_MimicShiner_C",
		},
		["BP_MiscBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Literature/BP_MiscBook.Default__BP_MiscBook_C",
		},
		["BP_MiscMagazine_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Literature/BP_MiscMagazine.Default__BP_MiscMagazine_C",
		},
		["BP_Mooneyes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Mooneyes/BP_Mooneyes.Default__BP_Mooneyes_C",
		},
		["BP_MottledSculpin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sculpins/BP_MottledSculpin.Default__BP_MottledSculpin_C",
		},
		["BP_MRE_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Military/BP_MRE.Default__BP_MRE_C",
		},
		["BP_Mudpuppy_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Amphibians/Salamanders/BP_Mudpuppy.Default__BP_Mudpuppy_C",
		},
		["BP_Muffin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Muffin.Default__BP_Muffin_C",
		},
		["BP_Mugwort_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_Mugwort.Default__BP_Mugwort_C",
		},
		["BP_Muskellunge_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/PikeMudminnows/BP_Muskellunge.Default__BP_Muskellunge_C",
		},
		["BP_NewOrleansOysters_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_NewOrleansOysters.Default__BP_NewOrleansOysters_C",
		},
		["BP_NorthernBrookLamprey_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Lampreys/BP_NorthernBrookLamprey.Default__BP_NorthernBrookLamprey_C",
		},
		["BP_NorthernPearlDace_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_NorthernPearlDace.Default__BP_NorthernPearlDace_C",
		},
		["BP_NorthernPike_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/PikeMudminnows/BP_NorthernPike.Default__BP_NorthernPike_C",
		},
		["BP_NorthernRedbellyDace_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_NorthernRedbellyDace.Default__BP_NorthernRedbellyDace_C",
		},
		["BP_NutsAlmonds_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_NutsAlmonds.Default__BP_NutsAlmonds_C",
		},
		["BP_NutsCashews_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_NutsCashews.Default__BP_NutsCashews_C",
		},
		["BP_NutsHazelnuts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_NutsHazelnuts.Default__BP_NutsHazelnuts_C",
		},
		["BP_NutsPeanuts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_NutsPeanuts.Default__BP_NutsPeanuts_C",
		},
		["BP_NutsPistachios_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_NutsPistachios.Default__BP_NutsPistachios_C",
		},
		["BP_NutsWalnuts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_NutsWalnuts.Default__BP_NutsWalnuts_C",
		},
		["BP_Omelette_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_Omelette.Default__BP_Omelette_C",
		},
		["BP_Onion_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Onion.Default__BP_Onion_C",
		},
		["BP_OnionHalf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_OnionHalf.Default__BP_OnionHalf_C",
		},
		["BP_OnionSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_OnionSoup.Default__BP_OnionSoup_C",
		},
		["BP_Orange_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Orange.Default__BP_Orange_C",
		},
		["BP_OrangeWedge_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_OrangeWedge.Default__BP_OrangeWedge_C",
		},
		["BP_Oysters_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Rich/BP_Oysters.Default__BP_Oysters_C",
		},
		["BP_PastaBox01Penne_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_PastaBox01Penne.Default__BP_PastaBox01Penne_C",
		},
		["BP_PastaBox01ZitoniTagliati_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_PastaBox01ZitoniTagliati.Default__BP_PastaBox01ZitoniTagliati_C",
		},
		["BP_PastaBox02Spaghetti_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_PastaBox02Spaghetti.Default__BP_PastaBox02Spaghetti_C",
		},
		["BP_PatlicanliKebap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_PatlicanliKebap.Default__BP_PatlicanliKebap_C",
		},
		["BP_Peach_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Peach.Default__BP_Peach_C",
		},
		["BP_PeachHalf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_PeachHalf.Default__BP_PeachHalf_C",
		},
		["BP_PeanutButterJar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_PeanutButterJar.Default__BP_PeanutButterJar_C",
		},
		["BP_Pear_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Pear.Default__BP_Pear_C",
		},
		["BP_PearHalf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_PearHalf.Default__BP_PearHalf_C",
		},
		["BP_PetConditioner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_PetConditioner.Default__BP_PetConditioner_C",
		},
		["BP_PetPerfume_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_PetPerfume.Default__BP_PetPerfume_C",
		},
		["BP_PetShampoo_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_PetShampoo.Default__BP_PetShampoo_C",
		},
		["BP_PickerelFrog_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Amphibians/Frogs/BP_PickerelFrog.Default__BP_PickerelFrog_C",
		},
		["BP_PigFeed_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Outdoors/BP_PigFeed.Default__BP_PigFeed_C",
		},
		["BP_Pineapple_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Pineapple.Default__BP_Pineapple_C",
		},
		["BP_PizzaCrust_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_PizzaCrust.Default__BP_PizzaCrust_C",
		},
		["BP_PizzaFull_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pub_Bar_Pizzaria/BP_PizzaFull.Default__BP_PizzaFull_C",
		},
		["BP_PizzaSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pub_Bar_Pizzaria/BP_PizzaSlice.Default__BP_PizzaSlice_C",
		},
		["BP_Plum_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Plum.Default__BP_Plum_C",
		},
		["BP_PlumHalf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_PlumHalf.Default__BP_PlumHalf_C",
		},
		["BP_Pork_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Pork.Default__BP_Pork_C",
		},
		["BP_Potato_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Potato.Default__BP_Potato_C",
		},
		["BP_PotatoesAuGratin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/OvenDish/BP_PotatoesAuGratin.Default__BP_PotatoesAuGratin_C",
		},
		["BP_PotatoSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_PotatoSoup.Default__BP_PotatoSoup_C",
		},
		["BP_PotRoast_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/OvenDish/BP_PotRoast.Default__BP_PotRoast_C",
		},
		["BP_PowderDetergent_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Cleaning/BP_PowderDetergent.Default__BP_PowderDetergent_C",
		},
		["BP_Pretzel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pub_Bar_Pizzaria/BP_Pretzel.Default__BP_Pretzel_C",
		},
		["BP_PuffPastry_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_PuffPastry.Default__BP_PuffPastry_C",
		},
		["BP_Pumpkin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Pumpkin.Default__BP_Pumpkin_C",
		},
		["BP_Pumpkin_JackOLantern_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Pumpkin_JackOLantern.Default__BP_Pumpkin_JackOLantern_C",
		},
		["BP_Pumpkinseed_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sunfishes/BP_Pumpkinseed.Default__BP_Pumpkinseed_C",
		},
		["BP_PumpkinSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_PumpkinSoup.Default__BP_PumpkinSoup_C",
		},
		["BP_PurpleConeflower_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_PurpleConeflower.Default__BP_PurpleConeflower_C",
		},
		["BP_QuesadillaBeef_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_QuesadillaBeef.Default__BP_QuesadillaBeef_C",
		},
		["BP_QuesadillaChicken_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_QuesadillaChicken.Default__BP_QuesadillaChicken_C",
		},
		["BP_Quiche_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/OvenDish/BP_Quiche.Default__BP_Quiche_C",
		},
		["BP_Quillback_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Suckers/BP_Quillback.Default__BP_Quillback_C",
		},
		["BP_RabbitMeat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_RabbitMeat.Default__BP_RabbitMeat_C",
		},
		["BP_RainbowSmelt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Smelts/BP_RainbowSmelt.Default__BP_RainbowSmelt_C",
		},
		["BP_RainbowTrout_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_RainbowTrout.Default__BP_RainbowTrout_C",
		},
		["BP_RanchBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Pantry/BP_RanchBottle.Default__BP_RanchBottle_C",
		},
		["BP_RedbreastSunfish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sunfishes/BP_RedbreastSunfish.Default__BP_RedbreastSunfish_C",
		},
		["BP_RedElderberry_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_RedElderberry.Default__BP_RedElderberry_C",
		},
		["BP_RedElderberryJam_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Refined/BP_RedElderberryJam.Default__BP_RedElderberryJam_C",
		},
		["BP_RedfinPickerel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/PikeMudminnows/BP_RedfinPickerel.Default__BP_RedfinPickerel_C",
		},
		["BP_RiceBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_RiceBag.Default__BP_RiceBag_C",
		},
		["BP_RicePilaf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/PotOrPan/BP_RicePilaf.Default__BP_RicePilaf_C",
		},
		["BP_RiceSnack_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_RiceSnack.Default__BP_RiceSnack_C",
		},
		["BP_Risotto_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/PotOrPan/BP_Risotto.Default__BP_Risotto_C",
		},
		["BP_RockBass_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sunfishes/BP_RockBass.Default__BP_RockBass_C",
		},
		["BP_RollAndouille_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_RollAndouille.Default__BP_RollAndouille_C",
		},
		["BP_RollBratWurst_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_RollBratWurst.Default__BP_RollBratWurst_C",
		},
		["BP_RosyfaceShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_RosyfaceShiner.Default__BP_RosyfaceShiner_C",
		},
		["BP_RoundWhitefish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_RoundWhitefish.Default__BP_RoundWhitefish_C",
		},
		["BP_RubbingAlcohol_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Medical/BP_RubbingAlcohol.Default__BP_RubbingAlcohol_C",
		},
		["BP_Rudd_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_Rudd.Default__BP_Rudd_C",
		},
		["BP_Saffron_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_Saffron.Default__BP_Saffron_C",
		},
		["BP_Sage_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_Sage.Default__BP_Sage_C",
		},
		["BP_SaltPack01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_SaltPack01.Default__BP_SaltPack01_C",
		},
		["BP_SandShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_SandShiner.Default__BP_SandShiner_C",
		},
		["BP_Sauger_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_Sauger.Default__BP_Sauger_C",
		},
		["BP_Sausages_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Sausages.Default__BP_Sausages_C",
		},
		["BP_Scallops_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Rich/BP_Scallops.Default__BP_Scallops_C",
		},
		["BP_SeaLamprey_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Lampreys/BP_SeaLamprey.Default__BP_SeaLamprey_C",
		},
		["BP_Shampoo_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_Shampoo.Default__BP_Shampoo_C",
		},
		["BP_ShinyLobsterMedallions_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_ShinyLobsterMedallions.Default__BP_ShinyLobsterMedallions_C",
		},
		["BP_ShortheadRedhorse_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Suckers/BP_ShortheadRedhorse.Default__BP_ShortheadRedhorse_C",
		},
		["BP_SilverLamprey_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Lampreys/BP_SilverLamprey.Default__BP_SilverLamprey_C",
		},
		["BP_SilverRedhorse_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Suckers/BP_SilverRedhorse.Default__BP_SilverRedhorse_C",
		},
		["BP_SlimySculpin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sculpins/BP_SlimySculpin.Default__BP_SlimySculpin_C",
		},
		["BP_SmallmouthBass_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sunfishes/BP_SmallmouthBass.Default__BP_SmallmouthBass_C",
		},
		["BP_SmallSodaBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_SmallSodaBottle.Default__BP_SmallSodaBottle_C",
		},
		["BP_SmallWaterBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_SmallWaterBottle.Default__BP_SmallWaterBottle_C",
		},
		["BP_SockeyeSalmon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_SockeyeSalmon.Default__BP_SockeyeSalmon_C",
		},
		["BP_SodaCan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_SodaCan.Default__BP_SodaCan_C",
		},
		["BP_Sourdough_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Bakery/BP_Sourdough.Default__BP_Sourdough_C",
		},
		["BP_SpaghettiCarbonara_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_SpaghettiCarbonara.Default__BP_SpaghettiCarbonara_C",
		},
		["BP_SpicyScrambledEggs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_SpicyScrambledEggs.Default__BP_SpicyScrambledEggs_C",
		},
		["BP_Spider_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Spider.Default__BP_Spider_C",
		},
		["BP_Splake_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trouts/BP_Splake.Default__BP_Splake_C",
		},
		["BP_SpotfinShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_SpotfinShiner.Default__BP_SpotfinShiner_C",
		},
		["BP_SpottailShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_SpottailShiner.Default__BP_SpottailShiner_C",
		},
		["BP_SprayBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_SprayBottle.Default__BP_SprayBottle_C",
		},
		["BP_Squash_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Squash.Default__BP_Squash_C",
		},
		["BP_SquashHalf_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_SquashHalf.Default__BP_SquashHalf_C",
		},
		["BP_SquashSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_SquashSoup.Default__BP_SquashSoup_C",
		},
		["BP_SteamedBunHotdog_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_SteamedBunHotdog.Default__BP_SteamedBunHotdog_C",
		},
		["BP_Steroid_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Drugs/BP_Steroid.Default__BP_Steroid_C",
		},
		["BP_Stomach_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_Stomach.Default__BP_Stomach_C",
		},
		["BP_Stonecat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Catfishes/BP_Stonecat.Default__BP_Stonecat_C",
		},
		["BP_StripedShiner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_StripedShiner.Default__BP_StripedShiner_C",
		},
		["BP_SugarBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_SugarBag.Default__BP_SugarBag_C",
		},
		["BP_SummerSucker_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Suckers/BP_SummerSucker.Default__BP_SummerSucker_C",
		},
		["BP_Sunscreen_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Outdoors/BP_Sunscreen.Default__BP_Sunscreen_C",
		},
		["BP_SweetPotato_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_SweetPotato.Default__BP_SweetPotato_C",
		},
		["BP_TadpoleMadtom_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Catfishes/BP_TadpoleMadtom.Default__BP_TadpoleMadtom_C",
		},
		["BP_Takoyaki_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_Takoyaki.Default__BP_Takoyaki_C",
		},
		["BP_TeaPackets_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_TeaPackets.Default__BP_TeaPackets_C",
		},
		["BP_Tench_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/MinnowsCarp/BP_Tench.Default__BP_Tench_C",
		},
		["BP_TessellatedDarter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_TessellatedDarter.Default__BP_TessellatedDarter_C",
		},
		["BP_TigerMuskellunge_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/PikeMudminnows/BP_TigerMuskellunge.Default__BP_TigerMuskellunge_C",
		},
		["BP_ToiletCleaner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/Cleaning/BP_ToiletCleaner.Default__BP_ToiletCleaner_C",
		},
		["BP_Tomato_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Tomato.Default__BP_Tomato_C",
		},
		["BP_TomatoSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_TomatoSlice.Default__BP_TomatoSlice_C",
		},
		["BP_TomatoSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_TomatoSoup.Default__BP_TomatoSoup_C",
		},
		["BP_Toothpaste_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Cleaning/BP_Toothpaste.Default__BP_Toothpaste_C",
		},
		["BP_Trout-perch_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Trout-perches/BP_Trout-perch.Default__BP_Trout-perch_C",
		},
		["BP_UndescribedSucker_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Suckers/BP_UndescribedSucker.Default__BP_UndescribedSucker_C",
		},
		["BP_UnidentifiedCavefish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Catfishes/BP_UnidentifiedCavefish.Default__BP_UnidentifiedCavefish_C",
		},
		["BP_VanillaManukaMeringue_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_VanillaManukaMeringue.Default__BP_VanillaManukaMeringue_C",
		},
		["BP_VegetableStirFry_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_VegetableStirFry.Default__BP_VegetableStirFry_C",
		},
		["BP_VeggieFat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_VeggieFat.Default__BP_VeggieFat_C",
		},
		["BP_Vichyssoise_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pot/BP_Vichyssoise.Default__BP_Vichyssoise_C",
		},
		["BP_VodkaBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_VodkaBottle.Default__BP_VodkaBottle_C",
		},
		["BP_Waffles_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Pan/BP_Waffles.Default__BP_Waffles_C",
		},
		["BP_WagyuBeef_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Rich/BP_WagyuBeef.Default__BP_WagyuBeef_C",
		},
		["BP_Walleye_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_Walleye.Default__BP_Walleye_C",
		},
		["BP_WaterDispenser_Bottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_WaterDispenser_Bottle.Default__BP_WaterDispenser_Bottle_C",
		},
		["BP_WaterFilter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Cleaning/BP_WaterFilter.Default__BP_WaterFilter_C",
		},
		["BP_Watermelon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Fruit_Veggies/BP_Watermelon.Default__BP_Watermelon_C",
		},
		["BP_WatermelonRind_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_WatermelonRind.Default__BP_WatermelonRind_C",
		},
		["BP_WatermelonSlice_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Trashed_Food/BP_WatermelonSlice.Default__BP_WatermelonSlice_C",
		},
		["BP_WhiskeyBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_WhiskeyBottle.Default__BP_WhiskeyBottle_C",
		},
		["BP_WhiteCrappie_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Sunfishes/BP_WhiteCrappie.Default__BP_WhiteCrappie_C",
		},
		["BP_WhitePerch_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/TemperateBasses/BP_WhitePerch.Default__BP_WhitePerch_C",
		},
		["BP_WhiteSucker_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Suckers/BP_WhiteSucker.Default__BP_WhiteSucker_C",
		},
		["BP_WhiteTruffles_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/Rich/BP_WhiteTruffles.Default__BP_WhiteTruffles_C",
		},
		["BP_WhiteTruffleWagyu_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/CookedDishes/Rich/BP_WhiteTruffleWagyu.Default__BP_WhiteTruffleWagyu_C",
		},
		["BP_WildBlackberries_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_WildBlackberries.Default__BP_WildBlackberries_C",
		},
		["BP_WildBlackberryJam_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Refined/BP_WildBlackberryJam.Default__BP_WildBlackberryJam_C",
		},
		["BP_WildGarlic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_WildGarlic.Default__BP_WildGarlic_C",
		},
		["BP_WildGarlicSalve_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Refined/BP_WildGarlicSalve.Default__BP_WildGarlicSalve_C",
		},
		["BP_WildGinger_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_WildGinger.Default__BP_WildGinger_C",
		},
		["BP_WildGingerSalve_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Refined/BP_WildGingerSalve.Default__BP_WildGingerSalve_C",
		},
		["BP_WineBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_WineBottle.Default__BP_WineBottle_C",
		},
		["BP_WitchsHat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_WitchsHat.Default__BP_WitchsHat_C",
		},
		["BP_WitchsHatSoup_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Refined/BP_WitchsHatSoup.Default__BP_WitchsHatSoup_C",
		},
		["BP_WolfMeat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/BP_WolfMeat.Default__BP_WolfMeat_C",
		},
		["BP_Yarrow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/BP_Yarrow.Default__BP_Yarrow_C",
		},
		["BP_YarrowSalve_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Foraging/Refined/BP_YarrowSalve.Default__BP_YarrowSalve_C",
		},
		["BP_YeastBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Pantry/BP_YeastBag.Default__BP_YeastBag_C",
		},
		["BP_YellowBullhead_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Catfishes/BP_YellowBullhead.Default__BP_YellowBullhead_C",
		},
		["BP_YellowPerch_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/Meat/Fish/Perches/BP_YellowPerch.Default__BP_YellowPerch_C",
		},
		["BP_ZombieHoneyJar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Consumables/01Drink/BP_ZombieHoneyJar.Default__BP_ZombieHoneyJar_C",
		},
}
