-- crafting.lua
return {
		["BP_AdvancedComponents_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,  --true/false
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/00_Parts/BP_AdvancedComponents.Default__BP_AdvancedComponents_C",
		},
		["BP_AdvancedTechParts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_AdvancedTechParts.Default__BP_AdvancedTechParts_C",
		},
		["BP_Alternator_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_Alternator.Default__BP_Alternator_C",
		},
		["BP_AluminumFoil_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/00_Parts/BP_AluminumFoil.Default__BP_AluminumFoil_C",
		},
		["BP_AluminumIngot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Smelted/BP_AluminumIngot.Default__BP_AluminumIngot_C",
		},
		["BP_AluminumScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_AluminumScrap.Default__BP_AluminumScrap_C",
		},
		["BP_Amplifier_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Amplifier.Default__BP_Amplifier_C",
		},
		["BP_Bandage_Makeshift_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Medical/BP_Bandage_Makeshift.Default__BP_Bandage_Makeshift_C",
		},
		["BP_BarbedWire_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_BarbedWire.Default__BP_BarbedWire_C",
		},
		["BP_BasicDriverBitBox_Tier3_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_BasicDriverBitBox_Tier3.Default__BP_BasicDriverBitBox_Tier3_C",
		},
		["BP_BasicStaples_Tier2_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_BasicStaples_Tier2.Default__BP_BasicStaples_Tier2_C",
		},
		["BP_BasicWeldingWire_Tier4_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_BasicWeldingWire_Tier4.Default__BP_BasicWeldingWire_Tier4_C",
		},
		["BP_Battery_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Battery.Default__BP_Battery_C",
		},
		["BP_BauxitePowder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_BauxitePowder.Default__BP_BauxitePowder_C",
		},
		["BP_Bones_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Bones.Default__BP_Bones_C",
		},
		["BP_BrakePad_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_BrakePad.Default__BP_BrakePad_C",
		},
		["BP_Capacitor_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/00_Parts/BP_Capacitor.Default__BP_Capacitor_C",
		},
		["BP_CarBattery_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarBattery.Default__BP_CarBattery_C",
		},
		["BP_CarBrakeAssembly_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarBrakeAssembly.Default__BP_CarBrakeAssembly_C",
		},
		["BP_CarChassisParts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarChassisParts.Default__BP_CarChassisParts_C",
		},
		["BP_CardboardScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_CardboardScrap.Default__BP_CardboardScrap_C",
		},
		["BP_CarEngine_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarEngine.Default__BP_CarEngine_C",
		},
		["BP_CarFilter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarFilter.Default__BP_CarFilter_C",
		},
		["BP_CarGasTank_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarGasTank.Default__BP_CarGasTank_C",
		},
		["BP_CarTire_AllWeather_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarTire_AllWeather.Default__BP_CarTire_AllWeather_C",
		},
		["BP_CarTire_OffRoad_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarTire_OffRoad.Default__BP_CarTire_OffRoad_C",
		},
		["BP_CarTire_Sport_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarTire_Sport.Default__BP_CarTire_Sport_C",
		},
		["BP_CarTire_Winter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_CarTire_Winter.Default__BP_CarTire_Winter_C",
		},
		["BP_Charcoal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Charcoal.Default__BP_Charcoal_C",
		},
		["BP_CircularSawBlade_Tier3_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_CircularSawBlade_Tier3.Default__BP_CircularSawBlade_Tier3_C",
		},
		["BP_ClothRope_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_ClothRope.Default__BP_ClothRope_C",
		},
		["BP_ClothScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_ClothScrap.Default__BP_ClothScrap_C",
		},
		["BP_Coke_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Coke.Default__BP_Coke_C",
		},
		["BP_Compass_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Gadgets/BP_Compass.Default__BP_Compass_C",
		},
		["BP_Components_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/00_Parts/BP_Components.Default__BP_Components_C",
		},
		["BP_ConcreteBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_ConcreteBag.Default__BP_ConcreteBag_C",
		},
		["BP_ConcretePaste_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/00_Parts/BP_ConcretePaste.Default__BP_ConcretePaste_C",
		},
		["BP_CopperIngot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Smelted/BP_CopperIngot.Default__BP_CopperIngot_C",
		},
		["BP_CopperWire_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/00_Parts/BP_CopperWire.Default__BP_CopperWire_C",
		},
		["BP_Crystal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Crystal.Default__BP_Crystal_C",
		},
		["BP_DenimScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_DenimScrap.Default__BP_DenimScrap_C",
		},
		["BP_DrillBitBox_Tier4_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_DrillBitBox_Tier4.Default__BP_DrillBitBox_Tier4_C",
		},
		["BP_DuctTape_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_DuctTape.Default__BP_DuctTape_C",
		},
		["BP_ElectricalScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_ElectricalScrap.Default__BP_ElectricalScrap_C",
		},
		["BP_EngineExhaustAssembly_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_EngineExhaustAssembly.Default__BP_EngineExhaustAssembly_C",
		},
		["BP_EngineIntakeManifold_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_EngineIntakeManifold.Default__BP_EngineIntakeManifold_C",
		},
		["BP_EnginePistonAssembly_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_EnginePistonAssembly.Default__BP_EnginePistonAssembly_C",
		},
		["BP_EngineSparkPlugs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_EngineSparkPlugs.Default__BP_EngineSparkPlugs_C",
		},
		["BP_EngineTimingBelts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Car/BP_EngineTimingBelts.Default__BP_EngineTimingBelts_C",
		},
		["BP_FanBlade_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_FanBlade.Default__BP_FanBlade_C",
		},
		["BP_Feathers_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Feathers.Default__BP_Feathers_C",
		},
		["BP_FishingLine_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Gadgets/BP_FishingLine.Default__BP_FishingLine_C",
		},
		["BP_FishingReel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Gadgets/BP_FishingReel.Default__BP_FishingReel_C",
		},
		["BP_FridgeCompressor_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_FridgeCompressor.Default__BP_FridgeCompressor_C",
		},
		["BP_FurPelt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_FurPelt.Default__BP_FurPelt_C",
		},
		["BP_GasCan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_GasCan.Default__BP_GasCan_C",
		},
		["BP_GlassShard_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_GlassShard.Default__BP_GlassShard_C",
		},
		["BP_GlassSheet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Smelted/BP_GlassSheet.Default__BP_GlassSheet_C",
		},
		["BP_GlueBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_GlueBottle.Default__BP_GlueBottle_C",
		},
		["BP_GPS_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Gadgets/BP_GPS.Default__BP_GPS_C",
		},
		["BP_GraphitePowder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_GraphitePowder.Default__BP_GraphitePowder_C",
		},
		["BP_GrinderBlade_Tier5_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_GrinderBlade_Tier5.Default__BP_GrinderBlade_Tier5_C",
		},
		["BP_Gunpowder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Chemistry/BP_Gunpowder.Default__BP_Gunpowder_C",
		},
		["BP_HandgunParts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_HandgunParts.Default__BP_HandgunParts_C",
		},
		["BP_HardLeatherStrips_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_HardLeatherStrips.Default__BP_HardLeatherStrips_C",
		},
		["BP_HeavyBolt_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_HeavyBolt.Default__BP_HeavyBolt_C",
		},
		["BP_HeavyStaples_Tier3_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_HeavyStaples_Tier3.Default__BP_HeavyStaples_Tier3_C",
		},
		["BP_IndustrialDriverBitBox_Tier4_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_IndustrialDriverBitBox_Tier4.Default__BP_IndustrialDriverBitBox_Tier4_C",
		},
		["BP_IndustrialStaples_Tier4_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_IndustrialStaples_Tier4.Default__BP_IndustrialStaples_Tier4_C",
		},
		["BP_IndustrialWeldingWire_Tier5_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_IndustrialWeldingWire_Tier5.Default__BP_IndustrialWeldingWire_Tier5_C",
		},
		["BP_IronIngot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Smelted/BP_IronIngot.Default__BP_IronIngot_C",
		},
		["BP_IronIngotHiGrade_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Smelted/BP_IronIngotHiGrade.Default__BP_IronIngotHiGrade_C",
		},
		["BP_IronScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_IronScrap.Default__BP_IronScrap_C",
		},
		["BP_JewelryScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_JewelryScrap.Default__BP_JewelryScrap_C",
		},
		["BP_JigsawBlade_Tier3_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/ToolAmmo/BP_JigsawBlade_Tier3.Default__BP_JigsawBlade_Tier3_C",
		},
		["BP_Kindling_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Miscellaneous/BP_Kindling.Default__BP_Kindling_C",
		},
		["BP_LauncherParts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_LauncherParts.Default__BP_LauncherParts_C",
		},
		["BP_LeatherStrips_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_LeatherStrips.Default__BP_LeatherStrips_C",
		},
		["BP_Lens_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Lens.Default__BP_Lens_C",
		},
		["BP_Lightbulb_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Lightbulb.Default__BP_Lightbulb_C",
		},
		["BP_LimestoneBrick_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Smelted/BP_LimestoneBrick.Default__BP_LimestoneBrick_C",
		},
		["BP_LimestoneChunks_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_LimestoneChunks.Default__BP_LimestoneChunks_C",
		},
		["BP_LimestonePowder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_LimestonePowder.Default__BP_LimestonePowder_C",
		},
		["BP_Log_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Log.Default__BP_Log_C",
		},
		["BP_MeatBait_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Survivalism/BP_MeatBait.Default__BP_MeatBait_C",
		},
		["BP_MedicinalScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_MedicinalScrap.Default__BP_MedicinalScrap_C",
		},
		["BP_MetalBrackets_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_MetalBrackets.Default__BP_MetalBrackets_C",
		},
		["BP_MetalPipe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_MetalPipe.Default__BP_MetalPipe_C",
		},
		["BP_MetalSheet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_MetalSheet.Default__BP_MetalSheet_C",
		},
		["BP_MetalSheetSmall_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_MetalSheetSmall.Default__BP_MetalSheetSmall_C",
		},
		["BP_ModelSun_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_ModelSun.Default__BP_ModelSun_C",
		},
		["BP_Nail_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Nail.Default__BP_Nail_C",
		},
		["BP_Needle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Needle.Default__BP_Needle_C",
		},
		["BP_NeedleThread_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_NeedleThread.Default__BP_NeedleThread_C",
		},
		["BP_Notepad_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Gadgets/BP_Notepad.Default__BP_Notepad_C",
		},
		["BP_OxygenDetector_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Gadgets/BP_OxygenDetector.Default__BP_OxygenDetector_C",
		},
		["BP_PaperScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_PaperScrap.Default__BP_PaperScrap_C",
		},
		["BP_ParaAramidFiber_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_ParaAramidFiber.Default__BP_ParaAramidFiber_C",
		},
		["BP_PlasticCasings_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/00_Parts/BP_PlasticCasings.Default__BP_PlasticCasings_C",
		},
		["BP_PlasticIngot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Smelted/BP_PlasticIngot.Default__BP_PlasticIngot_C",
		},
		["BP_PlasticScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_PlasticScrap.Default__BP_PlasticScrap_C",
		},
		["BP_PotentMedicinalScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_PotentMedicinalScrap.Default__BP_PotentMedicinalScrap_C",
		},
		["BP_RadioReceiver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RadioReceiver.Default__BP_RadioReceiver_C",
		},
		["BP_RadioTransmitter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RadioTransmitter.Default__BP_RadioTransmitter_C",
		},
		["BP_RawBauxite_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawBauxite.Default__BP_RawBauxite_C",
		},
		["BP_RawChalcopyrite_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawChalcopyrite.Default__BP_RawChalcopyrite_C",
		},
		["BP_RawCoal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawCoal.Default__BP_RawCoal_C",
		},
		["BP_RawFur_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawFur.Default__BP_RawFur_C",
		},
		["BP_RawGraphite_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawGraphite.Default__BP_RawGraphite_C",
		},
		["BP_RawHardLeather_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawHardLeather.Default__BP_RawHardLeather_C",
		},
		["BP_RawHematite_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawHematite.Default__BP_RawHematite_C",
		},
		["BP_RawLeather_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawLeather.Default__BP_RawLeather_C",
		},
		["BP_RawLimestone_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawLimestone.Default__BP_RawLimestone_C",
		},
		["BP_RawSilicaSand_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RawSilicaSand.Default__BP_RawSilicaSand_C",
		},
		["BP_RefinedCharcoal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_RefinedCharcoal.Default__BP_RefinedCharcoal_C",
		},
		["BP_ReinforcedMetalBrackets_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_ReinforcedMetalBrackets.Default__BP_ReinforcedMetalBrackets_C",
		},
		["BP_RemoteControllerT1_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Gadgets/BP_RemoteControllerT1.Default__BP_RemoteControllerT1_C",
		},
		["BP_RifleParts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_RifleParts.Default__BP_RifleParts_C",
		},
		["BP_RubberBundle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/00_Parts/BP_RubberBundle.Default__BP_RubberBundle_C",
		},
		["BP_RubberScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_RubberScrap.Default__BP_RubberScrap_C",
		},
		["BP_SawDust_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Miscellaneous/BP_SawDust.Default__BP_SawDust_C",
		},
		["BP_ScrapMetalPipe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_ScrapMetalPipe.Default__BP_ScrapMetalPipe_C",
		},
		["BP_ScrapMetalSheet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_ScrapMetalSheet.Default__BP_ScrapMetalSheet_C",
		},
		["BP_ScrapMetalSheetSmall_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_ScrapMetalSheetSmall.Default__BP_ScrapMetalSheetSmall_C",
		},
		["BP_Screw_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Screw.Default__BP_Screw_C",
		},
		["BP_SewingMachine_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_SewingMachine.Default__BP_SewingMachine_C",
		},
		["BP_ShotgunParts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_ShotgunParts.Default__BP_ShotgunParts_C",
		},
		["BP_Splint_Makeshift_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Medical/BP_Splint_Makeshift.Default__BP_Splint_Makeshift_C",
		},
		["BP_Springs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Springs.Default__BP_Springs_C",
		},
		["BP_SteelIngot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Smelted/BP_SteelIngot.Default__BP_SteelIngot_C",
		},
		["BP_SteelScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_SteelScrap.Default__BP_SteelScrap_C",
		},
		["BP_StoveHeatingElements_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_StoveHeatingElements.Default__BP_StoveHeatingElements_C",
		},
		["BP_Sulfur_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Sulfur.Default__BP_Sulfur_C",
		},
		["BP_Thread_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Thread.Default__BP_Thread_C",
		},
		["BP_TVInverter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_TVInverter.Default__BP_TVInverter_C",
		},
		["BP_VolatilePowder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Chemistry/BP_VolatilePowder.Default__BP_VolatilePowder_C",
		},
		["BP_WaterSkin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Crafted/Gadgets/BP_WaterSkin.Default__BP_WaterSkin_C",
		},
		["BP_Wax_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_Wax.Default__BP_Wax_C",
		},
		["BP_WireBundle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_WireBundle.Default__BP_WireBundle_C",
		},
		["BP_WoodenRod_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_WoodenRod.Default__BP_WoodenRod_C",
		},
		["BP_WoodenRodReinforced_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/BP_WoodenRodReinforced.Default__BP_WoodenRodReinforced_C",
		},
		["BP_WoodScrap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Crafting/Scrap/BP_WoodScrap.Default__BP_WoodScrap_C",
		},
}
