-- farming.lua
return {
		["BP_Bloodmeal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Bloodmeal.Default__BP_Bloodmeal_C",
		},
		["BP_Bonemeal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Bonemeal.Default__BP_Bonemeal_C",
		},
		["BP_Compost_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Compost.Default__BP_Compost_C",
		},
		["BP_DeadPlant_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_DeadPlant.Default__BP_DeadPlant_C",
		},
		["BP_Seeds_Apple_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Apple.Default__BP_Seeds_Apple_C",
		},
		["BP_Seeds_Artichoke_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Artichoke.Default__BP_Seeds_Artichoke_C",
		},
		["BP_Seeds_Broccoli_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Broccoli.Default__BP_Seeds_Broccoli_C",
		},
		["BP_Seeds_Cabbage_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Cabbage.Default__BP_Seeds_Cabbage_C",
		},
		["BP_Seeds_Cannabis_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Cannabis.Default__BP_Seeds_Cannabis_C",
		},
		["BP_Seeds_Carrot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Carrot.Default__BP_Seeds_Carrot_C",
		},
		["BP_Seeds_Cauliflower_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Cauliflower.Default__BP_Seeds_Cauliflower_C",
		},
		["BP_Seeds_Corn_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Corn.Default__BP_Seeds_Corn_C",
		},
		["BP_Seeds_Cucumber_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Cucumber.Default__BP_Seeds_Cucumber_C",
		},
		["BP_Seeds_Eggplant_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Eggplant.Default__BP_Seeds_Eggplant_C",
		},
		["BP_Seeds_Garlic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Garlic.Default__BP_Seeds_Garlic_C",
		},
		["BP_Seeds_Onion_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Onion.Default__BP_Seeds_Onion_C",
		},
		["BP_Seeds_Potato_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Potato.Default__BP_Seeds_Potato_C",
		},
		["BP_Seeds_Pumpkin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Pumpkin.Default__BP_Seeds_Pumpkin_C",
		},
		["BP_Seeds_Squash_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Squash.Default__BP_Seeds_Squash_C",
		},
		["BP_Seeds_SweetPotato_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_SweetPotato.Default__BP_Seeds_SweetPotato_C",
		},
		["BP_Seeds_Tomato_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Tomato.Default__BP_Seeds_Tomato_C",
		},
		["BP_Seeds_Watermelon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_Seeds_Watermelon.Default__BP_Seeds_Watermelon_C",
		},
		["BP_SoilBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_SoilBag.Default__BP_SoilBag_C",
		},
		["BP_UngrownPlant_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Farming/BP_UngrownPlant.Default__BP_UngrownPlant_C",
		},
}
