return {
		["BP_Ashes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Trash/BP_Ashes.Default__BP_Ashes_C",
		},
		["BP_BarCodeScanner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_BarCodeScanner.Default__BP_BarCodeScanner_C",
		},
		["BP_BarSoap_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Bathroom/BP_BarSoap.Default__BP_BarSoap_C",
		},
		["BP_Baseball_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_Baseball.Default__BP_Baseball_C",
		},
		["BP_Basin01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Basin01.Default__BP_Basin01_C",
		},
		["BP_Basin02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Basin02.Default__BP_Basin02_C",
		},
		["BP_Basketball_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_Basketball.Default__BP_Basketball_C",
		},
		["BP_BathroomScale_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Bathroom/BP_BathroomScale.Default__BP_BathroomScale_C",
		},
		["BP_Bible_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Church/BP_Bible.Default__BP_Bible_C",
		},
		["BP_Binder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Binder.Default__BP_Binder_C",
		},
		["BP_Birdie_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_Birdie.Default__BP_Birdie_C",
		},
		["BP_BloodPressure01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_BloodPressure01.Default__BP_BloodPressure01_C",
		},
		["BP_Book_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Book.Default__BP_Book_C",
		},
		["BP_Bowl_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_Bowl.Default__BP_Bowl_C",
		},
		["BP_BroadcastRadio_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_BroadcastRadio.Default__BP_BroadcastRadio_C",
		},
		["BP_BroadcastRadioItemInstance_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_BroadcastRadioItemInstance.Default__BP_BroadcastRadioItemInstance_C",
		},
		["BP_Broom_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Broom.Default__BP_Broom_C",
		},
		["BP_Bucket01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Bucket01.Default__BP_Bucket01_C",
		},
		["BP_Bucket02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Bucket02.Default__BP_Bucket02_C",
		},
		["BP_Bucket03_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Bucket03.Default__BP_Bucket03_C",
		},
		["BP_Bucket04_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Bucket04.Default__BP_Bucket04_C",
		},
		["BP_Bucket05_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Bucket05.Default__BP_Bucket05_C",
		},
		["BP_Bucket06_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Bucket06.Default__BP_Bucket06_C",
		},
		["BP_Bucket07_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Bucket07.Default__BP_Bucket07_C",
		},
		["BP_Bucket08_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Bucket08.Default__BP_Bucket08_C",
		},
		["BP_Bugspray_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_Bugspray.Default__BP_Bugspray_C",
		},
		["BP_BunsenTripod01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_BunsenTripod01.Default__BP_BunsenTripod01_C",
		},
		["BP_Calculator_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Calculator.Default__BP_Calculator_C",
		},
		["BP_CampBowl_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_CampBowl.Default__BP_CampBowl_C",
		},
		["BP_CampCoffeePot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_CampCoffeePot.Default__BP_CampCoffeePot_C",
		},
		["BP_CampMug_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_CampMug.Default__BP_CampMug_C",
		},
		["BP_Chalk_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Chalk.Default__BP_Chalk_C",
		},
		["BP_ChessBoard_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_ChessBoard.Default__BP_ChessBoard_C",
		},
		["BP_Clock_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Clock.Default__BP_Clock_C",
		},
		["BP_CoffeePot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_CoffeePot.Default__BP_CoffeePot_C",
		},
		["BP_Comb_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Barber/BP_Comb.Default__BP_Comb_C",
		},
		["BP_CookingPot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_CookingPot.Default__BP_CookingPot_C",
		},
		["BP_Dart_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_Dart.Default__BP_Dart_C",
		},
		["BP_DartBoard_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_DartBoard.Default__BP_DartBoard_C",
		},
		["BP_DefendantSign_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Court/BP_DefendantSign.Default__BP_DefendantSign_C",
		},
		["BP_Diapers_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/Pantry/BP_Diapers.Default__BP_Diapers_C",
		},
		["BP_DustPan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_DustPan.Default__BP_DustPan_C",
		},
		["BP_EmptyTinCan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Trash/BP_EmptyTinCan.Default__BP_EmptyTinCan_C",
		},
		["BP_Eraser_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Eraser.Default__BP_Eraser_C",
		},
		["BP_Fan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Fan.Default__BP_Fan_C",
		},
		["BP_Flask01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Flask01.Default__BP_Flask01_C",
		},
		["BP_Flask02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Flask02.Default__BP_Flask02_C",
		},
		["BP_Flask03_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Flask03.Default__BP_Flask03_C",
		},
		["BP_Flask04_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Flask04.Default__BP_Flask04_C",
		},
		["BP_Flask05_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Flask05.Default__BP_Flask05_C",
		},
		["BP_Flask06_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Flask06.Default__BP_Flask06_C",
		},
		["BP_Flask07_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Flask07.Default__BP_Flask07_C",
		},
		["BP_FloodLight_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_FloodLight.Default__BP_FloodLight_C",
		},
		["BP_FolderEmpty_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_FolderEmpty.Default__BP_FolderEmpty_C",
		},
		["BP_FolderFull_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_FolderFull.Default__BP_FolderFull_C",
		},
		["BP_Football_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_Football.Default__BP_Football_C",
		},
		["BP_Forceps_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_Forceps.Default__BP_Forceps_C",
		},
		["BP_GameConsole_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_GameConsole.Default__BP_GameConsole_C",
		},
		["BP_GameController_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_GameController.Default__BP_GameController_C",
		},
		["BP_GameHandheld_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_GameHandheld.Default__BP_GameHandheld_C",
		},
		["BP_Globe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_Globe.Default__BP_Globe_C",
		},
		["BP_Glowstick_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_Glowstick.Default__BP_Glowstick_C",
		},
		["BP_GolfBall_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_GolfBall.Default__BP_GolfBall_C",
		},
		["BP_GolfTee_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_GolfTee.Default__BP_GolfTee_C",
		},
		["BP_Gore_Arm_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Gore/BP_Gore_Arm.Default__BP_Gore_Arm_C",
		},
		["BP_Gore_Foot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Gore/BP_Gore_Foot.Default__BP_Gore_Foot_C",
		},
		["BP_GreaseCleaner_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_GreaseCleaner.Default__BP_GreaseCleaner_C",
		},
		["BP_Hairdryer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Bathroom/BP_Hairdryer.Default__BP_Hairdryer_C",
		},
		["BP_HairRoll_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Barber/BP_HairRoll.Default__BP_HairRoll_C",
		},
		["BP_HairRollerKit_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Barber/BP_HairRollerKit.Default__BP_HairRollerKit_C",
		},
		["BP_HairSpray_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Barber/BP_HairSpray.Default__BP_HairSpray_C",
		},
		["BP_Handcuffs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Prison/BP_Handcuffs.Default__BP_Handcuffs_C",
		},
		["BP_Hanger_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_Hanger.Default__BP_Hanger_C",
		},
		["BP_HockeyPuck_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_HockeyPuck.Default__BP_HockeyPuck_C",
		},
		["BP_HolePuncher_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_HolePuncher.Default__BP_HolePuncher_C",
		},
		["BP_HymnsBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Church/BP_HymnsBook.Default__BP_HymnsBook_C",
		},
		["BP_Kettle01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_Kettle01.Default__BP_Kettle01_C",
		},
		["BP_Kettle02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_Kettle02.Default__BP_Kettle02_C",
		},
		["BP_Lantern_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_Lantern.Default__BP_Lantern_C",
		},
		["BP_LargeBrush_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_LargeBrush.Default__BP_LargeBrush_C",
		},
		["BP_LargeCoffeePot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_LargeCoffeePot.Default__BP_LargeCoffeePot_C",
		},
		["BP_LeafBlower_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_LeafBlower.Default__BP_LeafBlower_C",
		},
		["BP_Lifering01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_Lifering01.Default__BP_Lifering01_C",
		},
		["BP_MagicToyBall_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_MagicToyBall.Default__BP_MagicToyBall_C",
		},
		["BP_Marker_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Marker.Default__BP_Marker_C",
		},
		["BP_MaskBox_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/Packages/BP_MaskBox.Default__BP_MaskBox_C",
		},
		["BP_MeatSlicer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_MeatSlicer.Default__BP_MeatSlicer_C",
		},
		["BP_MedicalScraper01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_MedicalScraper01.Default__BP_MedicalScraper01_C",
		},
		["BP_MedicalScraper02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_MedicalScraper02.Default__BP_MedicalScraper02_C",
		},
		["BP_Microscope_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Microscope.Default__BP_Microscope_C",
		},
		["BP_MopBucket01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_MopBucket01.Default__BP_MopBucket01_C",
		},
		["BP_Mouse_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Mouse.Default__BP_Mouse_C",
		},
		["BP_Mousepad_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Mousepad.Default__BP_Mousepad_C",
		},
		["BP_Mug_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_Mug.Default__BP_Mug_C",
		},
		["BP_Mug_GameDev_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_Mug_GameDev.Default__BP_Mug_GameDev_C",
		},
		["BP_NapkinHolder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_NapkinHolder.Default__BP_NapkinHolder_C",
		},
		["BP_Newspaper_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Trash/BP_Newspaper.Default__BP_Newspaper_C",
		},
		["BP_NewtonsCradle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_NewtonsCradle.Default__BP_NewtonsCradle_C",
		},
		["BP_OvenDish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_OvenDish.Default__BP_OvenDish_C",
		},
		["BP_PaintTray_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_PaintTray.Default__BP_PaintTray_C",
		},
		["BP_PaperBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Trash/BP_PaperBag.Default__BP_PaperBag_C",
		},
		["BP_Parcel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/Packages/BP_Parcel.Default__BP_Parcel_C",
		},
		["BP_PastaMaker_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_PastaMaker.Default__BP_PastaMaker_C",
		},
		["BP_PC_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_PC.Default__BP_PC_C",
		},
		["BP_Pen_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Pen.Default__BP_Pen_C",
		},
		["BP_PenBin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_PenBin.Default__BP_PenBin_C",
		},
		["BP_Pencil_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Pencil.Default__BP_Pencil_C",
		},
		["BP_PencilSharpener_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_PencilSharpener.Default__BP_PencilSharpener_C",
		},
		["BP_PetBrush_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_PetBrush.Default__BP_PetBrush_C",
		},
		["BP_PetCatToyBell_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_PetCatToyBell.Default__BP_PetCatToyBell_C",
		},
		["BP_PetDeshedder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_PetDeshedder.Default__BP_PetDeshedder_C",
		},
		["BP_PetLeash_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_PetLeash.Default__BP_PetLeash_C",
		},
		["BP_PetNailClipper_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_PetNailClipper.Default__BP_PetNailClipper_C",
		},
		["BP_PetriDish01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_PetriDish01.Default__BP_PetriDish01_C",
		},
		["BP_Phone_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Phone.Default__BP_Phone_C",
		},
		["BP_PhotoFrame_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PhotoFrame.Default__BP_PhotoFrame_C",
		},
		["BP_PizzaBox_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_PizzaBox.Default__BP_PizzaBox_C",
		},
		["BP_Plate_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_Plate.Default__BP_Plate_C",
		},
		["BP_Pomade_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Barber/BP_Pomade.Default__BP_Pomade_C",
		},
		["BP_PoolBall01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall01.Default__BP_PoolBall01_C",
		},
		["BP_PoolBall02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall02.Default__BP_PoolBall02_C",
		},
		["BP_PoolBall03_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall03.Default__BP_PoolBall03_C",
		},
		["BP_PoolBall04_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall04.Default__BP_PoolBall04_C",
		},
		["BP_PoolBall05_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall05.Default__BP_PoolBall05_C",
		},
		["BP_PoolBall06_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall06.Default__BP_PoolBall06_C",
		},
		["BP_PoolBall07_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall07.Default__BP_PoolBall07_C",
		},
		["BP_PoolBall08_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall08.Default__BP_PoolBall08_C",
		},
		["BP_PoolBall09_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall09.Default__BP_PoolBall09_C",
		},
		["BP_PoolBall10_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall10.Default__BP_PoolBall10_C",
		},
		["BP_PoolBall11_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall11.Default__BP_PoolBall11_C",
		},
		["BP_PoolBall12_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall12.Default__BP_PoolBall12_C",
		},
		["BP_PoolBall13_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall13.Default__BP_PoolBall13_C",
		},
		["BP_PoolBall14_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall14.Default__BP_PoolBall14_C",
		},
		["BP_PoolBall15_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolBall15.Default__BP_PoolBall15_C",
		},
		["BP_PoolRack_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PoolRack.Default__BP_PoolRack_C",
		},
		["BP_Printer01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Printer01.Default__BP_Printer01_C",
		},
		["BP_Printer02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Printer02.Default__BP_Printer02_C",
		},
		["BP_ProsecutionSign_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Court/BP_ProsecutionSign.Default__BP_ProsecutionSign_C",
		},
		["BP_Protractor_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_Protractor.Default__BP_Protractor_C",
		},
		["BP_PuzzleCube_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_PuzzleCube.Default__BP_PuzzleCube_C",
		},
		["BP_Razor_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Barber/BP_Razor.Default__BP_Razor_C",
		},
		["BP_ReceiptPaper_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_ReceiptPaper.Default__BP_ReceiptPaper_C",
		},
		["BP_ReceiptPrinter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_ReceiptPrinter.Default__BP_ReceiptPrinter_C",
		},
		["BP_Record_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_Record.Default__BP_Record_C",
		},
		["BP_RecordPlayer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_RecordPlayer.Default__BP_RecordPlayer_C",
		},
		["BP_Retractor01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_Retractor01.Default__BP_Retractor01_C",
		},
		["BP_Retractor02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_Retractor02.Default__BP_Retractor02_C",
		},
		["BP_RingStand01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/School/BP_RingStand01.Default__BP_RingStand01_C",
		},
		["BP_Rosary_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Church/BP_Rosary.Default__BP_Rosary_C",
		},
		["BP_Ruler_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Ruler.Default__BP_Ruler_C",
		},
		["BP_Sander_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Sander.Default__BP_Sander_C",
		},
		["BP_Scale01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_Scale01.Default__BP_Scale01_C",
		},
		["BP_ShaveBrush_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Barber/BP_ShaveBrush.Default__BP_ShaveBrush_C",
		},
		["BP_ShoppingBasket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_ShoppingBasket.Default__BP_ShoppingBasket_C",
		},
		["BP_SoccerBall_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Outdoor/BP_SoccerBall.Default__BP_SoccerBall_C",
		},
		["BP_Sponge_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Dining/BP_Sponge.Default__BP_Sponge_C",
		},
		["BP_SprayCan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_SprayCan.Default__BP_SprayCan_C",
		},
		["BP_SteelWool_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Store/BP_SteelWool.Default__BP_SteelWool_C",
		},
		["BP_Stethoscope01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_Stethoscope01.Default__BP_Stethoscope01_C",
		},
		["BP_StringTrimmer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_StringTrimmer.Default__BP_StringTrimmer_C",
		},
		["BP_SurgeProtector_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_SurgeProtector.Default__BP_SurgeProtector_C",
		},
		["BP_SurgicalTray01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_SurgicalTray01.Default__BP_SurgicalTray01_C",
		},
		["BP_SurgicalTray02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_SurgicalTray02.Default__BP_SurgicalTray02_C",
		},
		["BP_TapeDispenser_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Office/BP_TapeDispenser.Default__BP_TapeDispenser_C",
		},
		["BP_Tissues_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/Pantry/BP_Tissues.Default__BP_Tissues_C",
		},
		["BP_ToiletBrush_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Bathroom/BP_ToiletBrush.Default__BP_ToiletBrush_C",
		},
		["BP_ToiletPaper_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Bathroom/BP_ToiletPaper.Default__BP_ToiletPaper_C",
		},
		["BP_Toothbrush_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Bathroom/BP_Toothbrush.Default__BP_Toothbrush_C",
		},
		["BP_Towel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Bathroom/BP_Towel.Default__BP_Towel_C",
		},
		["BP_ToyRocket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_ToyRocket.Default__BP_ToyRocket_C",
		},
		["BP_Tracker_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_Tracker.Default__BP_Tracker_C",
		},
		["BP_Trophy_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Residential/BP_Trophy.Default__BP_Trophy_C",
		},
		["BP_Tweezers_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Medical/BP_Tweezers.Default__BP_Tweezers_C",
		},
		["BP_Washboard_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Bathroom/BP_Washboard.Default__BP_Washboard_C",
		},
		["BP_WitnessSign_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Court/BP_WitnessSign.Default__BP_WitnessSign_C",
		},
		["BP_Worklight_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Junk/Industrial/BP_Worklight.Default__BP_Worklight_C",
		},
}
