-- medical.lua
return {
		["BP_AntiAnxietyPills_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_AntiAnxietyPills.Default__BP_AntiAnxietyPills_C",
		},
		["BP_Antibiotic_Advanced_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Antibiotic_Advanced.Default__BP_Antibiotic_Advanced_C",
		},
		["BP_Antibiotic_Basic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Antibiotic_Basic.Default__BP_Antibiotic_Basic_C",
		},
		["BP_Antibiotic_Veterinary_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_Antibiotic_Veterinary.Default__BP_Antibiotic_Veterinary_C",
		},
		["BP_AntiDepressants_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_AntiDepressants.Default__BP_AntiDepressants_C",
		},
		["BP_AntiDepressants_Veterinary_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_AntiDepressants_Veterinary.Default__BP_AntiDepressants_Veterinary_C",
		},
		["BP_AntineoplasticMedication_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_AntineoplasticMedication.Default__BP_AntineoplasticMedication_C",
		},
		["BP_AntiRad_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_AntiRad.Default__BP_AntiRad_C",
		},
		["BP_Bandage_Compression_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Bandage_Compression.Default__BP_Bandage_Compression_C",
		},
		["BP_Bandage_Elastic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Bandage_Elastic.Default__BP_Bandage_Elastic_C",
		},
		["BP_Bandage_Trauma_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Bandage_Trauma.Default__BP_Bandage_Trauma_C",
		},
		["BP_BloodBag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_BloodBag.Default__BP_BloodBag_C",
		},
		["BP_BloodTestKit_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_BloodTestKit.Default__BP_BloodTestKit_C",
		},
		["BP_Burncream_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Burncream.Default__BP_Burncream_C",
		},
		["BP_CaffeinePills_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_CaffeinePills.Default__BP_CaffeinePills_C",
		},
		["BP_CharcoalTabs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_CharcoalTabs.Default__BP_CharcoalTabs_C",
		},
		["BP_CleaningWipes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_CleaningWipes.Default__BP_CleaningWipes_C",
		},
		["BP_DewormerMedication01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_DewormerMedication01.Default__BP_DewormerMedication01_C",
		},
		["BP_DewormerMedication02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_DewormerMedication02.Default__BP_DewormerMedication02_C",
		},
		["BP_EDMedication_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_EDMedication.Default__BP_EDMedication_C",
		},
		["BP_FirstAidKit_Clinic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Packages/BP_FirstAidKit_Clinic.Default__BP_FirstAidKit_Clinic_C",
		},
		["BP_FirstAidKit_Military_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Packages/BP_FirstAidKit_Military.Default__BP_FirstAidKit_Military_C",
		},
		["BP_FirstAidKit_Personal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Packages/BP_FirstAidKit_Personal.Default__BP_FirstAidKit_Personal_C",
		},
		["BP_FirstAidKit_Survival_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Packages/BP_FirstAidKit_Survival.Default__BP_FirstAidKit_Survival_C",
		},
		["BP_FleaMedication_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_FleaMedication.Default__BP_FleaMedication_C",
		},
		["BP_HandSanitizer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_HandSanitizer.Default__BP_HandSanitizer_C",
		},
		["BP_Insulin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Insulin.Default__BP_Insulin_C",
		},
		["BP_ItchCream_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_ItchCream.Default__BP_ItchCream_C",
		},
		["BP_Painkillers_Basic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Painkillers_Basic.Default__BP_Painkillers_Basic_C",
		},
		["BP_Painkillers_Morphine_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Painkillers_Morphine.Default__BP_Painkillers_Morphine_C",
		},
		["BP_Painkillers_Prescription_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Painkillers_Prescription.Default__BP_Painkillers_Prescription_C",
		},
		["BP_Painkillers_Veterinary_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_Painkillers_Veterinary.Default__BP_Painkillers_Veterinary_C",
		},
		["BP_SleepGummies_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_SleepGummies.Default__BP_SleepGummies_C",
		},
		["BP_Splint_Medical_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Splint_Medical.Default__BP_Splint_Medical_C",
		},
		["BP_Splint_Veterinary_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_Splint_Veterinary.Default__BP_Splint_Veterinary_C",
		},
		["BP_Syringe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Syringe.Default__BP_Syringe_C",
		},
		["BP_UrinaryMedication_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/Vet/BP_UrinaryMedication.Default__BP_UrinaryMedication_C",
		},
		["BP_Zombrin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Medical/BP_Zombrin.Default__BP_Zombrin_C",
		},
}
