-- schematics.lua
return {
		["BP_SC_Amplifier_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Amplifier.Default__BP_SC_Amplifier_C",
		},
		["BP_SC_BarbedWire_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_BarbedWire.Default__BP_SC_BarbedWire_C",
		},
		["BP_SC_BasicCutting_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_BasicCutting.Default__BP_SC_BasicCutting_C",
		},
		["BP_SC_BasicDriverBits_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_BasicDriverBits.Default__BP_SC_BasicDriverBits_C",
		},
		["BP_SC_BasicPliers_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_BasicPliers.Default__BP_SC_BasicPliers_C",
		},
		["BP_SC_BasicStaples_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_BasicStaples.Default__BP_SC_BasicStaples_C",
		},
		["BP_SC_BasicWeldingWire_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_BasicWeldingWire.Default__BP_SC_BasicWeldingWire_C",
		},
		["BP_SC_Binoculars_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Binoculars.Default__BP_SC_Binoculars_C",
		},
		["BP_SC_BloodTestKit_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_BloodTestKit.Default__BP_SC_BloodTestKit_C",
		},
		["BP_SC_Bow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Bow.Default__BP_SC_Bow_C",
		},
		["BP_SC_CarBrakeAssembly_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CarBrakeAssembly.Default__BP_SC_CarBrakeAssembly_C",
		},
		["BP_SC_CarFilter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CarFilter.Default__BP_SC_CarFilter_C",
		},
		["BP_SC_CarGasTank_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CarGasTank.Default__BP_SC_CarGasTank_C",
		},
		["BP_SC_CircularSawBlade_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CircularSawBlade.Default__BP_SC_CircularSawBlade_C",
		},
		["BP_SC_CleaningWipes_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CleaningWipes.Default__BP_SC_CleaningWipes_C",
		},
		["BP_SC_Compass_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Compass.Default__BP_SC_Compass_C",
		},
		["BP_SC_CompressionBandage_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CompressionBandage.Default__BP_SC_CompressionBandage_C",
		},
		["BP_SC_CookbookLvl10_01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl10_01.Default__BP_SC_CookbookLvl10_01_C",
		},
		["BP_SC_CookbookLvl10_02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl10_02.Default__BP_SC_CookbookLvl10_02_C",
		},
		["BP_SC_CookbookLvl20_01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl20_01.Default__BP_SC_CookbookLvl20_01_C",
		},
		["BP_SC_CookbookLvl20_02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl20_02.Default__BP_SC_CookbookLvl20_02_C",
		},
		["BP_SC_CookbookLvl30_01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl30_01.Default__BP_SC_CookbookLvl30_01_C",
		},
		["BP_SC_CookbookLvl30_02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl30_02.Default__BP_SC_CookbookLvl30_02_C",
		},
		["BP_SC_CookbookLvl30_03_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl30_03.Default__BP_SC_CookbookLvl30_03_C",
		},
		["BP_SC_CookbookLvl40_01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl40_01.Default__BP_SC_CookbookLvl40_01_C",
		},
		["BP_SC_CookbookLvl40_02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl40_02.Default__BP_SC_CookbookLvl40_02_C",
		},
		["BP_SC_CookbookLvl60_01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl60_01.Default__BP_SC_CookbookLvl60_01_C",
		},
		["BP_SC_CookbookLvl80_01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl80_01.Default__BP_SC_CookbookLvl80_01_C",
		},
		["BP_SC_CookbookLvl80_02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/Cookbooks/BP_SC_CookbookLvl80_02.Default__BP_SC_CookbookLvl80_02_C",
		},
		["BP_SC_CookingDish_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CookingDish.Default__BP_SC_CookingDish_C",
		},
		["BP_SC_CookingPan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CookingPan.Default__BP_SC_CookingPan_C",
		},
		["BP_SC_CookingPot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_CookingPot.Default__BP_SC_CookingPot_C",
		},
		["BP_SC_DrillBit_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_DrillBit.Default__BP_SC_DrillBit_C",
		},
		["BP_SC_ElasticBandage_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_ElasticBandage.Default__BP_SC_ElasticBandage_C",
		},
		["BP_SC_Flashlight_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Flashlight.Default__BP_SC_Flashlight_C",
		},
		["BP_SC_FridgeCompressor_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_FridgeCompressor.Default__BP_SC_FridgeCompressor_C",
		},
		["BP_SC_GPS_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_GPS.Default__BP_SC_GPS_C",
		},
		["BP_SC_GrinderBlades_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_GrinderBlades.Default__BP_SC_GrinderBlades_C",
		},
		["BP_SC_Hammer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Hammer.Default__BP_SC_Hammer_C",
		},
		["BP_SC_HeavyBolts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_HeavyBolts.Default__BP_SC_HeavyBolts_C",
		},
		["BP_SC_HeavyCutting_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_HeavyCutting.Default__BP_SC_HeavyCutting_C",
		},
		["BP_SC_HeavyHammer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_HeavyHammer.Default__BP_SC_HeavyHammer_C",
		},
		["BP_SC_HeavyStaples_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_HeavyStaples.Default__BP_SC_HeavyStaples_C",
		},
		["BP_SC_IndustrialDriverBits_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_IndustrialDriverBits.Default__BP_SC_IndustrialDriverBits_C",
		},
		["BP_SC_IndustrialStaples_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_IndustrialStaples.Default__BP_SC_IndustrialStaples_C",
		},
		["BP_SC_IndustrialWeldingWire_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_IndustrialWeldingWire.Default__BP_SC_IndustrialWeldingWire_C",
		},
		["BP_SC_IronArrow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_IronArrow.Default__BP_SC_IronArrow_C",
		},
		["BP_SC_Lighter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Lighter.Default__BP_SC_Lighter_C",
		},
		["BP_SC_Lockpick_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Lockpick.Default__BP_SC_Lockpick_C",
		},
		["BP_SC_MakeshiftSword_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_MakeshiftSword.Default__BP_SC_MakeshiftSword_C",
		},
		["BP_SC_MedicalSplint_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_MedicalSplint.Default__BP_SC_MedicalSplint_C",
		},
		["BP_SC_MortarPestle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_MortarPestle.Default__BP_SC_MortarPestle_C",
		},
		["BP_SC_Nails_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Nails.Default__BP_SC_Nails_C",
		},
		["BP_SC_RadioReceiver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_RadioReceiver.Default__BP_SC_RadioReceiver_C",
		},
		["BP_SC_RadioTransmitter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_RadioTransmitter.Default__BP_SC_RadioTransmitter_C",
		},
		["BP_SC_Screwdriver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Screwdriver.Default__BP_SC_Screwdriver_C",
		},
		["BP_SC_Screws_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Screws.Default__BP_SC_Screws_C",
		},
		["BP_SC_SplintMakeshift_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_SplintMakeshift.Default__BP_SC_SplintMakeshift_C",
		},
		["BP_SC_Springs_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Springs.Default__BP_SC_Springs_C",
		},
		["BP_SC_StoveHeatingElements_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_StoveHeatingElements.Default__BP_SC_StoveHeatingElements_C",
		},
		["BP_SC_Syringe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_Syringe.Default__BP_SC_Syringe_C",
		},
		["BP_SC_TraumaBandage_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Schematics/BP_SC_TraumaBandage.Default__BP_SC_TraumaBandage_C",
		},
}
