-- skillmags.lua
return {
		["BP_AgilityBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_AgilityBook.Default__BP_AgilityBook_C",
		},
		["BP_AgilityMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_AgilityMag.Default__BP_AgilityMag_C",
		},
		["BP_ConstructionBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_ConstructionBook.Default__BP_ConstructionBook_C",
		},
		["BP_ConstructionMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_ConstructionMag.Default__BP_ConstructionMag_C",
		},
		["BP_CookingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_CookingBook.Default__BP_CookingBook_C",
		},
		["BP_CookingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_CookingMag.Default__BP_CookingMag_C",
		},
		["BP_CraftingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_CraftingBook.Default__BP_CraftingBook_C",
		},
		["BP_CraftingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_CraftingMag.Default__BP_CraftingMag_C",
		},
		["BP_DismantlingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_DismantlingBook.Default__BP_DismantlingBook_C",
		},
		["BP_DismantlingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_DismantlingMag.Default__BP_DismantlingMag_C",
		},
		["BP_DrivingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_DrivingBook.Default__BP_DrivingBook_C",
		},
		["BP_DrivingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_DrivingMag.Default__BP_DrivingMag_C",
		},
		["BP_ElectricalBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_ElectricalBook.Default__BP_ElectricalBook_C",
		},
		["BP_ElectricalMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_ElectricalMag.Default__BP_ElectricalMag_C",
		},
		["BP_FarmingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_FarmingBook.Default__BP_FarmingBook_C",
		},
		["BP_FarmingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_FarmingMag.Default__BP_FarmingMag_C",
		},
		["BP_LockpickingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_LockpickingBook.Default__BP_LockpickingBook_C",
		},
		["BP_LockpickingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_LockpickingMag.Default__BP_LockpickingMag_C",
		},
		["BP_MechanicalBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_MechanicalBook.Default__BP_MechanicalBook_C",
		},
		["BP_MechanicalMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_MechanicalMag.Default__BP_MechanicalMag_C",
		},
		["BP_MedicalBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_MedicalBook.Default__BP_MedicalBook_C",
		},
		["BP_MedicalMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_MedicalMag.Default__BP_MedicalMag_C",
		},
		["BP_RepairBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_RepairBook.Default__BP_RepairBook_C",
		},
		["BP_RepairMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_RepairMag.Default__BP_RepairMag_C",
		},
		["BP_ScavengingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_ScavengingBook.Default__BP_ScavengingBook_C",
		},
		["BP_ScavengingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_ScavengingMag.Default__BP_ScavengingMag_C",
		},
		["BP_SneakingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_SneakingBook.Default__BP_SneakingBook_C",
		},
		["BP_SneakingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_SneakingMag.Default__BP_SneakingMag_C",
		},
		["BP_SociabilityBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_SociabilityBook.Default__BP_SociabilityBook_C",
		},
		["BP_SociabilityMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_SociabilityMag.Default__BP_SociabilityMag_C",
		},
		["BP_StrengthBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_StrengthBook.Default__BP_StrengthBook_C",
		},
		["BP_StrengthMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_StrengthMag.Default__BP_StrengthMag_C",
		},
		["BP_ThrowingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_ThrowingBook.Default__BP_ThrowingBook_C",
		},
		["BP_ThrowingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_ThrowingMag.Default__BP_ThrowingMag_C",
		},
		["BP_TradingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_TradingBook.Default__BP_TradingBook_C",
		},
		["BP_TradingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_TradingMag.Default__BP_TradingMag_C",
		},
		["BP_VitalityBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_VitalityBook.Default__BP_VitalityBook_C",
		},
		["BP_VitalityMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_VitalityMag.Default__BP_VitalityMag_C",
		},
		["BP_WeaponHandlingBook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/SkillBooks/BP_WeaponHandlingBook.Default__BP_WeaponHandlingBook_C",
		},
		["BP_WeaponHandlingMag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/SkillMags/BP_WeaponHandlingMag.Default__BP_WeaponHandlingMag_C",
		},
}
