-- tools.lua
return {
		["BP_Binoculars_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Binoculars.Default__BP_Binoculars_C",
		},
		["BP_CellPhone_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_CellPhone.Default__BP_CellPhone_C",
		},
		["BP_CircularSaw_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_CircularSaw.Default__BP_CircularSaw_C",
		},
		["BP_ElectricDriver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_ElectricDriver.Default__BP_ElectricDriver_C",
		},
		["BP_FishGuts_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_FishGuts.Default__BP_FishGuts_C",
		},
		["BP_FishingBait_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_FishingBait.Default__BP_FishingBait_C",
		},
		["BP_FishingHook_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_FishingHook.Default__BP_FishingHook_C",
		},
		["BP_FishingRod_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_FishingRod.Default__BP_FishingRod_C",
		},
		["BP_Flashlight_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Flashlight.Default__BP_Flashlight_C",
		},
		["BP_FoldingChair_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_FoldingChair.Default__BP_FoldingChair_C",
		},
		["BP_GasCanister_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_GasCanister.Default__BP_GasCanister_C",
		},
		["BP_Grinder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Grinder.Default__BP_Grinder_C",
		},
		["BP_HandheldRadio_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_HandheldRadio.Default__BP_HandheldRadio_C",
		},
		["BP_HydraulicCutters_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_HydraulicCutters.Default__BP_HydraulicCutters_C",
		},
		["BP_HydraulicDriver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_HydraulicDriver.Default__BP_HydraulicDriver_C",
		},
		["BP_ImpactDrill_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_ImpactDrill.Default__BP_ImpactDrill_C",
		},
		["BP_ImpactDriver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_ImpactDriver.Default__BP_ImpactDriver_C",
		},
		["BP_Jigsaw_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Jigsaw.Default__BP_Jigsaw_C",
		},
		["BP_JumperCables_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_JumperCables.Default__BP_JumperCables_C",
		},
		["BP_KeroseneCanister_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_KeroseneCanister.Default__BP_KeroseneCanister_C",
		},
		["BP_LawnChair_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LawnChair.Default__BP_LawnChair_C",
		},
		["BP_Lighter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Lighter.Default__BP_Lighter_C",
		},
		["BP_LockCode_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LockCode.Default__BP_LockCode_C",
		},
		["BP_LockEnhanced_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LockEnhanced.Default__BP_LockEnhanced_C",
		},
		["BP_LockKey_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LockKey.Default__BP_LockKey_C",
		},
		["BP_Lockpick_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Lockpick.Default__BP_Lockpick_C",
		},
		["BP_LockSimple_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LockSimple.Default__BP_LockSimple_C",
		},
		["BP_LockStandard_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LockStandard.Default__BP_LockStandard_C",
		},
		["BP_LockTough_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LockTough.Default__BP_LockTough_C",
		},
		["BP_LockVerySimple_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LockVerySimple.Default__BP_LockVerySimple_C",
		},
		["BP_LockVeryTough_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_LockVeryTough.Default__BP_LockVeryTough_C",
		},
		["BP_Map_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Map.Default__BP_Map_C",
		},
		["BP_Matches_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Matches.Default__BP_Matches_C",
		},
		["BP_MortarPestle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_MortarPestle.Default__BP_MortarPestle_C",
		},
		["BP_Nailgun_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Nailgun.Default__BP_Nailgun_C",
		},
		["BP_PeristalticPump_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_PeristalticPump.Default__BP_PeristalticPump_C",
		},
		["BP_PetrolCutter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_PetrolCutter.Default__BP_PetrolCutter_C",
		},
		["BP_PlasticFoldingChair_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_PlasticFoldingChair.Default__BP_PlasticFoldingChair_C",
		},
		["BP_PortableCotBag01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_PortableCotBag01.Default__BP_PortableCotBag01_C",
		},
		["BP_SleepingBag01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_SleepingBag01.Default__BP_SleepingBag01_C",
		},
		["BP_SleepingBag02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_SleepingBag02.Default__BP_SleepingBag02_C",
		},
		["BP_SolderingIron_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_SolderingIron.Default__BP_SolderingIron_C",
		},
		["BP_StapleGun_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_StapleGun.Default__BP_StapleGun_C",
		},
		["BP_Stapler_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Stapler.Default__BP_Stapler_C",
		},
		["BP_Tent01_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Tent01.Default__BP_Tent01_C",
		},
		["BP_Tent02_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Tent02.Default__BP_Tent02_C",
		},
		["BP_Tent03_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Tent03.Default__BP_Tent03_C",
		},
		["BP_Thermometer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_Thermometer.Default__BP_Thermometer_C",
		},
		["BP_ToolBattery_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_ToolBattery.Default__BP_ToolBattery_C",
		},
		["BP_ToolBattery_HeavyDuty_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_ToolBattery_HeavyDuty.Default__BP_ToolBattery_HeavyDuty_C",
		},
		["BP_WateringCan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_WateringCan.Default__BP_WateringCan_C",
		},
		["BP_WelderHyperbaric_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_WelderHyperbaric.Default__BP_WelderHyperbaric_C",
		},
		["BP_WelderIndustrial_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_WelderIndustrial.Default__BP_WelderIndustrial_C",
		},
		["BP_WelderPortable_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Tools/BP_WelderPortable.Default__BP_WelderPortable_C",
		},
}
