-- weapons.lua
return {
		["BP_Arrow_Iron_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BowAndArrow/BP_Arrow_Iron.Default__BP_Arrow_Iron_C",
		},
		["BP_Arrow_Iron_Improved_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BowAndArrow/BP_Arrow_Iron_Improved.Default__BP_Arrow_Iron_Improved_C",
		},
		["BP_BondageWhip_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_BondageWhip.Default__BP_BondageWhip_C",
		},
		["BP_Bow_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BowAndArrow/BP_Bow.Default__BP_Bow_C",
		},
		["BP_Firearm_AK_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_AK.Default__BP_Firearm_AK_C",
		},
		["BP_Firearm_AT4_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_AT4.Default__BP_Firearm_AT4_C",
		},
		["BP_Firearm_Bolt1911_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_Bolt1911.Default__BP_Firearm_Bolt1911_C",
		},
		["BP_Firearm_BoltViper_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_BoltViper.Default__BP_Firearm_BoltViper_C",
		},
		["BP_Firearm_DoubleBarrel_BIG_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_DoubleBarrel_BIG.Default__BP_Firearm_DoubleBarrel_BIG_C",
		},
		["BP_Firearm_DoubleBarrel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_DoubleBarrel.Default__BP_Firearm_DoubleBarrel_C",
		},
		["BP_Firearm_FiftySeven_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_FiftySeven.Default__BP_Firearm_FiftySeven_C",
		},
		["BP_Firearm_FlareGun_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_FlareGun.Default__BP_Firearm_FlareGun_C",
		},
		["BP_Firearm_Flock17_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_Flock17.Default__BP_Firearm_Flock17_C",
		},
		["BP_Firearm_LaserGun_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_LaserGun.Default__BP_Firearm_LaserGun_C",
		},
		["BP_Firearm_LoneStar38_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_LoneStar38.Default__BP_Firearm_LoneStar38_C",
		},
		["BP_Firearm_Minigun_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_Minigun.Default__BP_Firearm_Minigun_C",
		},
		["BP_Firearm_MosinNagant_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_MosinNagant.Default__BP_Firearm_MosinNagant_C",
		},
		["BP_Firearm_MP5_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_MP5.Default__BP_Firearm_MP5_C",
		},
		["BP_Firearm_N16_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_N16.Default__BP_Firearm_N16_C",
		},
		["BP_Firearm_N1903_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_N1903.Default__BP_Firearm_N1903_C",
		},
		["BP_Firearm_P9_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_P9.Default__BP_Firearm_P9_C",
		},
		["BP_Firearm_PumpShotgun_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_PumpShotgun.Default__BP_Firearm_PumpShotgun_C",
		},
		["BP_Firearm_SRG_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_SRG.Default__BP_Firearm_SRG_C",
		},
		["BP_Firearm_Taser_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Ranged/BP_Firearm_Taser.Default__BP_Firearm_Taser_C",
		},
		["BP_Grenade_Dynamite_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Grenades/BP_Grenade_Dynamite.Default__BP_Grenade_Dynamite_C",
		},
		["BP_Grenade_DynamitePack_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Grenades/BP_Grenade_DynamitePack.Default__BP_Grenade_DynamitePack_C",
		},
		["BP_Grenade_Frag_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Grenades/BP_Grenade_Frag.Default__BP_Grenade_Frag_C",
		},
		["BP_Grenade_Hand_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Grenades/BP_Grenade_Hand.Default__BP_Grenade_Hand_C",
		},
		["BP_Melee_AxeFire_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_AxeFire.Default__BP_Melee_AxeFire_C",
		},
		["BP_Melee_AxeWood_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_AxeWood.Default__BP_Melee_AxeWood_C",
		},
		["BP_Melee_BadmintonRacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_BadmintonRacket.Default__BP_Melee_BadmintonRacket_C",
		},
		["BP_Melee_BarClamp_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_BarClamp.Default__BP_Melee_BarClamp_C",
		},
		["BP_Melee_BaseballBat_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_BaseballBat.Default__BP_Melee_BaseballBat_C",
		},
		["BP_Melee_BaseballBatSpiked_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_BaseballBatSpiked.Default__BP_Melee_BaseballBatSpiked_C",
		},
		["BP_Melee_BoltCutters_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_BoltCutters.Default__BP_Melee_BoltCutters_C",
		},
		["BP_Melee_BoneMallet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_BoneMallet.Default__BP_Melee_BoneMallet_C",
		},
		["BP_Melee_BrokenBottle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_BrokenBottle.Default__BP_Melee_BrokenBottle_C",
		},
		["BP_Melee_CastIronPan_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_CastIronPan.Default__BP_Melee_CastIronPan_C",
		},
		["BP_Melee_ClawHammer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_ClawHammer.Default__BP_Melee_ClawHammer_C",
		},
		["BP_Melee_ClawSword_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_ClawSword.Default__BP_Melee_ClawSword_C",
		},
		["BP_Melee_Cleaver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_Cleaver.Default__BP_Melee_Cleaver_C",
		},
		["BP_Melee_CombatKnife_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_CombatKnife.Default__BP_Melee_CombatKnife_C",
		},
		["BP_Melee_CombatShovel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_CombatShovel.Default__BP_Melee_CombatShovel_C",
		},
		["BP_Melee_CrossHeadScrewdriver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_CrossHeadScrewdriver.Default__BP_Melee_CrossHeadScrewdriver_C",
		},
		["BP_Melee_Crowbar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Crowbar.Default__BP_Melee_Crowbar_C",
		},
		["BP_Melee_CrystalDagger_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_CrystalDagger.Default__BP_Melee_CrystalDagger_C",
		},
		["BP_Melee_FiberglassPaddle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_FiberglassPaddle.Default__BP_Melee_FiberglassPaddle_C",
		},
		["BP_Melee_FireHookPike_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_FireHookPike.Default__BP_Melee_FireHookPike_C",
		},
		["BP_Melee_FlatHeadScrewdriver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_FlatHeadScrewdriver.Default__BP_Melee_FlatHeadScrewdriver_C",
		},
		["BP_Melee_FoamSword_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_FoamSword.Default__BP_Melee_FoamSword_C",
		},
		["BP_Melee_Fork_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Fork.Default__BP_Melee_Fork_C",
		},
		["BP_Melee_FryerBasket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_FryerBasket.Default__BP_Melee_FryerBasket_C",
		},
		["BP_Melee_GardenHoe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_GardenHoe.Default__BP_Melee_GardenHoe_C",
		},
		["BP_Melee_GolfClub_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_GolfClub.Default__BP_Melee_GolfClub_C",
		},
		["BP_Melee_Guitar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Instruments/BP_Melee_Guitar.Default__BP_Melee_Guitar_C",
		},
		["BP_Melee_HandBell_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Instruments/BP_Melee_HandBell.Default__BP_Melee_HandBell_C",
		},
		["BP_Melee_HeftyBone_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_HeftyBone.Default__BP_Melee_HeftyBone_C",
		},
		["BP_Melee_HockeyStick_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_HockeyStick.Default__BP_Melee_HockeyStick_C",
		},
		["BP_Melee_Keyboard_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Keyboard.Default__BP_Melee_Keyboard_C",
		},
		["BP_Melee_KnifeBread_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_KnifeBread.Default__BP_Melee_KnifeBread_C",
		},
		["BP_Melee_KnifeButter_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_KnifeButter.Default__BP_Melee_KnifeButter_C",
		},
		["BP_Melee_LawnmowerBlade_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_LawnmowerBlade.Default__BP_Melee_LawnmowerBlade_C",
		},
		["BP_Melee_Leveler_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Leveler.Default__BP_Melee_Leveler_C",
		},
		["BP_Melee_Machete_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_Machete.Default__BP_Melee_Machete_C",
		},
		["BP_Melee_MarshmallowStick_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_MarshmallowStick.Default__BP_Melee_MarshmallowStick_C",
		},
		["BP_Melee_Mop_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Mop.Default__BP_Melee_Mop_C",
		},
		["BP_Melee_MorningStar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_MorningStar.Default__BP_Melee_MorningStar_C",
		},
		["BP_Melee_OxygenCylinder_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_OxygenCylinder.Default__BP_Melee_OxygenCylinder_C",
		},
		["BP_Melee_PaintBrush_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_PaintBrush.Default__BP_Melee_PaintBrush_C",
		},
		["BP_Melee_PaintRoller_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_PaintRoller.Default__BP_Melee_PaintRoller_C",
		},
		["BP_Melee_PalletJack_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_PalletJack.Default__BP_Melee_PalletJack_C",
		},
		["BP_Melee_Pickaxe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_Pickaxe.Default__BP_Melee_Pickaxe_C",
		},
		["BP_Melee_PickaxeImproved_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_PickaxeImproved.Default__BP_Melee_PickaxeImproved_C",
		},
		["BP_Melee_PingPongRacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_PingPongRacket.Default__BP_Melee_PingPongRacket_C",
		},
		["BP_Melee_Pipe_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Pipe.Default__BP_Melee_Pipe_C",
		},
		["BP_Melee_PipeWrench_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_PipeWrench.Default__BP_Melee_PipeWrench_C",
		},
		["BP_Melee_PizzaPeel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_PizzaPeel.Default__BP_Melee_PizzaPeel_C",
		},
		["BP_Melee_Plank_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafting/BP_Melee_Plank.Default__BP_Melee_Plank_C",
		},
		["BP_Melee_PlankReinforced_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafting/BP_Melee_PlankReinforced.Default__BP_Melee_PlankReinforced_C",
		},
		["BP_Melee_PlankSpiked_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_PlankSpiked.Default__BP_Melee_PlankSpiked_C",
		},
		["BP_Melee_PliersCombination_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_PliersCombination.Default__BP_Melee_PliersCombination_C",
		},
		["BP_Melee_PliersLocking_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_PliersLocking.Default__BP_Melee_PliersLocking_C",
		},
		["BP_Melee_PliersTongueAndGroove_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_PliersTongueAndGroove.Default__BP_Melee_PliersTongueAndGroove_C",
		},
		["BP_Melee_Plunger_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Plunger.Default__BP_Melee_Plunger_C",
		},
		["BP_Melee_PoliceBaton_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_PoliceBaton.Default__BP_Melee_PoliceBaton_C",
		},
		["BP_Melee_PoolCue_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_PoolCue.Default__BP_Melee_PoolCue_C",
		},
		["BP_Melee_PropaneTank_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_PropaneTank.Default__BP_Melee_PropaneTank_C",
		},
		["BP_Melee_RakeMetal_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_RakeMetal.Default__BP_Melee_RakeMetal_C",
		},
		["BP_Melee_RakePlastic_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_RakePlastic.Default__BP_Melee_RakePlastic_C",
		},
		["BP_Melee_SaleSign_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_SaleSign.Default__BP_Melee_SaleSign_C",
		},
		["BP_Melee_SaucePot_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_SaucePot.Default__BP_Melee_SaucePot_C",
		},
		["BP_Melee_SawCrosscut_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_SawCrosscut.Default__BP_Melee_SawCrosscut_C",
		},
		["BP_Melee_SawHack_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_SawHack.Default__BP_Melee_SawHack_C",
		},
		["BP_Melee_Scalpel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_Scalpel.Default__BP_Melee_Scalpel_C",
		},
		["BP_Melee_Scissors_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_Scissors.Default__BP_Melee_Scissors_C",
		},
		["BP_Melee_Shiv_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_Shiv.Default__BP_Melee_Shiv_C",
		},
		["BP_Melee_Shovel_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_Shovel.Default__BP_Melee_Shovel_C",
		},
		["BP_Melee_SledgeHammer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_SledgeHammer.Default__BP_Melee_SledgeHammer_C",
		},
		["BP_Melee_SledgehammerMini_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_SledgehammerMini.Default__BP_Melee_SledgehammerMini_C",
		},
		["BP_Melee_Spatula_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Spatula.Default__BP_Melee_Spatula_C",
		},
		["BP_Melee_Spoon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Spoon.Default__BP_Melee_Spoon_C",
		},
		["BP_Melee_SteelChair_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_SteelChair.Default__BP_Melee_SteelChair_C",
		},
		["BP_Melee_StraightRazor_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_StraightRazor.Default__BP_Melee_StraightRazor_C",
		},
		["BP_Melee_Strainer_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Strainer.Default__BP_Melee_Strainer_C",
		},
		["BP_Melee_TennisRacket_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_TennisRacket.Default__BP_Melee_TennisRacket_C",
		},
		["BP_Melee_Thumbtack_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Thumbtack.Default__BP_Melee_Thumbtack_C",
		},
		["BP_Melee_Tomahawk_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_Tomahawk.Default__BP_Melee_Tomahawk_C",
		},
		["BP_Melee_Trumpet_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Instruments/BP_Melee_Trumpet.Default__BP_Melee_Trumpet_C",
		},
		["BP_Melee_Violin_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Instruments/BP_Melee_Violin.Default__BP_Melee_Violin_C",
		},
		["BP_Melee_WetFloorSign_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_WetFloorSign.Default__BP_Melee_WetFloorSign_C",
		},
		["BP_Melee_Whisk_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_Whisk.Default__BP_Melee_Whisk_C",
		},
		["BP_Melee_WoodenOar_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Sports/BP_Melee_WoodenOar.Default__BP_Melee_WoodenOar_C",
		},
		["BP_Melee_WoodenOarSpiked_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenOarSpiked.Default__BP_Melee_WoodenOarSpiked_C",
		},
		["BP_Melee_WoodenSpear_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpear.Default__BP_Melee_WoodenSpear_C",
		},
		["BP_Melee_WoodenSpearButterKnife_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearButterKnife.Default__BP_Melee_WoodenSpearButterKnife_C",
		},
		["BP_Melee_WoodenSpearCombatKnife_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearCombatKnife.Default__BP_Melee_WoodenSpearCombatKnife_C",
		},
		["BP_Melee_WoodenSpearFork_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearFork.Default__BP_Melee_WoodenSpearFork_C",
		},
		["BP_Melee_WoodenSpearKnife_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearKnife.Default__BP_Melee_WoodenSpearKnife_C",
		},
		["BP_Melee_WoodenSpearMachete_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearMachete.Default__BP_Melee_WoodenSpearMachete_C",
		},
		["BP_Melee_WoodenSpearScissors_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearScissors.Default__BP_Melee_WoodenSpearScissors_C",
		},
		["BP_Melee_WoodenSpearScrewdriver_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearScrewdriver.Default__BP_Melee_WoodenSpearScrewdriver_C",
		},
		["BP_Melee_WoodenSpearSpoon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearSpoon.Default__BP_Melee_WoodenSpearSpoon_C",
		},
		["BP_Melee_WoodenSpearThumbtack_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/Crafted/BP_Melee_WoodenSpearThumbtack.Default__BP_Melee_WoodenSpearThumbtack_C",
		},
		["BP_Melee_WoodenSpoon_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/BP_Melee_WoodenSpoon.Default__BP_Melee_WoodenSpoon_C",
		},
		["BP_Melee_Wrench_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Melee/MeleeTools/BP_Melee_Wrench.Default__BP_Melee_Wrench_C",
		},
		["BP_RedDotSight_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Attachments/BP_RedDotSight.Default__BP_RedDotSight_C",
		},
		["BP_Suppressor_Pistol_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Attachments/BP_Suppressor_Pistol.Default__BP_Suppressor_Pistol_C",
		},
		["BP_Suppressor_Rifle_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Attachments/BP_Suppressor_Rifle.Default__BP_Suppressor_Rifle_C",
		},
		["BP_VerticalGrip_C"] = {
			Weight      = nil,
			MaxStack    = nil,
			bStackable  = nil,
			_CDOPath = "/Game/Vein/Items/Weapons/Attachments/BP_VerticalGrip.Default__BP_VerticalGrip_C",
		},	
}
